### ISSUE TITLE
Ability to integrate KVS into ReactJS?

### ISSUE THREAD

**Issue by nhockool1002** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#100]
I'm currently working on to be able to integrate AWS KVS into ReactJS for project use, about integration I don't know if you guys feel good or not, I am struggling and do not understand many issues. During integration, I wonder if the develop team has an example for my case. Thank you very much.

**Comment by lherman-cs** [comment]
@nhockool1002 This is not a a dedicated example, but we have a similar issue thread here, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/45#issuecomment-629308809. It contains a working React example.

**Comment by lherman-cs** [comment]
Since we don't currently have a plan to create an official example any time soon, I'll mark this as resolved. Please use the attached example as a reference only.
