### ISSUE TITLE
No REMB packets fired to WebRTC C master after adding "viewer.peerConnection.addTransceiver('video', {'direction': 'sendrecv'})"

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#101]
For some obscure reason that I don't understand, I had to add a line of viewer.peerConnection.addTransceiver('video', {'direction': 'sendrecv'}) in order for some browsers to be able to decode WebRTC h264 properly. But once I do that no REMB packets are feedback into the WebRTC master. Seems like there's a dilemma here.
If I want to support more browsers, I have to drop REMB bandwidth estimation.
If I want to keep REMB bandwidth estimation, I have to drop cross browser support.

**Comment by suggestedfixes** [comment]
browser that does not give REMB:
chrome:  86.0.4240.75

browser with REMB
firefox: 81.0.2 

I'm beginning to think I should have posted on the c sdk github.

**Comment by suggestedfixes** [comment]
Reproduced on windows 7 with 86.0.4240.75
Cannot be reproduced with windows 10 with 86.0.4240.75

**Comment by MushMal** [comment]
I am not certain this is signaling client or JS sample related question. Looks more like a webrtc implementation question which  is orthogonal to this project. Please confirm and close.

**Comment by suggestedfixes** [comment]
It might have to be related to C SDK parsing because of different os. Gathering information.

**Comment by suggestedfixes** [comment]
Actually, it's very likely that windows 7 with chrome cannot decode with the stock example.

**Comment by suggestedfixes** [comment]
Let's solve the decoding problem, then REMB
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/896
