### ISSUE TITLE
Signaling error

### ISSUE THREAD

**Issue by flex225** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#102]
Hi, I'm getting error like this  as viewer. I've also tried demo  that you've implemented, same error.
```
ERROR] [VIEWER] Signaling client error:  {
  "isTrusted": true
}
```
Can you help me with this?
Thank you.

**Comment by MushMal** [comment]
Double check your credentials and ensure they have proper permission/rights for the channel.

@lherman-cs any further suggestions on how to debug the issue?

**Comment by flex225** [comment]
Yeah, I figured out it and forgot to close. Thank you
