### ISSUE TITLE
close() does not properly teardown websocket

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#103]
It was found that we have to click 'close viewer' twice to make the subsequent connection more successful. A closer inspection on close() function reveals that there are two parts to close() function. As you can see, the first call closes the websocket, and the second call to close actually calls the cleanup handler.

```
   public close(): void {
        if (this.websocket !== null) {
            this.readyState = ReadyState.CLOSING;
            this.websocket.close();
        } else if (this.readyState !== ReadyState.CLOSED) {
            this.onClose();
        }
    }
```

**Comment by sirknightj** [comment]
Hey @suggestedfixes,

When the call to [`this.websocket.close()`](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/close) finishes, it will also emit the `close` event, which we are listening to:
```
        this.websocket.addEventListener('close', this.onClose);
```

I have confirmed this by adding a `console.log` to the onClose method, and it is printed each time I press "close viewer".
```javascript
    private onClose(): void {
        console.log('onClose() ------------- !!');
        this.readyState = ReadyState.CLOSED;
        this.cleanupWebSocket();
        this.emit('close');
    }
```

The flow:
1. close()
2. onClose()
  a. cleanupWebSocket()

**Comment by sirknightj** [comment]
Feel free to reach out if you have any other questions or concerns
