### ISSUE TITLE
Where is master.remoteStreams used?

### ISSUE THREAD

**Issue by matwerber1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#104]
Hi, 

In the `stopMaster()` function, there is a line that says:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/749e5d231fd88ddf82545e84ae22f8578c1b6ae7/examples/master.js#L231

However, I don't see anywhere else where we actually use `master.remoteStreams`, apart from the empty initialization at the top of `master.js`:

```
const master = {
    signalingClient: null,
    peerConnectionByClientId: {},
    dataChannelByClientId: {},
    localStream: null,
    remoteStreams: [],
    peerConnectionStatsInterval: null,
};
```

I'm working on converting this demo to React, so just trying to make sure I'm covering everything.

**Comment by HimanshuVerma18111989** [comment]
@matwerber1 can you share your react code if you are done with implementation?

**Comment by matwerber1** [comment]
Sure, see here: 
https://github.com/matwerber1/aws-kinesisvideo-webrtc-react

I admit, I don't know React or WebRTC well, so its possible there may be some mistakes... but I was able to get viewer and master working with a signaling channel so seems to be at least most of the way there.

**Comment by MushMal** [comment]
It's not being used currently. The idea is to enhance it for multi-viewer client support in the future.

I am going to resolve this issue but please keep iterating over the reactjs if you need.
