### ISSUE TITLE
Any webRTC code for master which does not use browser APIs?

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#105]
Hi Experts,

I was trying to use this sdk on node js server side. I can see the are a lot of APIs being used in sdk which are not available on the node js server side. Is there another sdk available which can be used on node js server side?

**Comment by MushMal** [comment]
Readme has some information: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/749e5d231fd88ddf82545e84ae22f8578c1b6ae7/README.md#in-nodejs

There is also compatibility section.
