### ISSUE TITLE
Streaming IP camera using example code.

### ISSUE THREAD

**Issue by HimanshuVerma18111989** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#106]
Hi Team,

I am willing to use this sdk-js for access KVSWebRTC for our onsite camera video streaming. I want to run this code on the server which is reading the camera stream (rtsp) from a port. While i was porting this code to be run on server side, i came to know that we are using a lot of browser APIs for access web cameras. Can you suggest me how can i stream rtsp camera using this code? I am currently struggling with how to get stream out of rtsp camera so that i can integrate it with this code?

**Comment by MushMal** [comment]
JS SDK really is about the signaling client. The actual webrtc implementation is inside the browser. You might need to look into the browsers implementation.

Alternatively, you could use our own implementation of C-based webrtc for your service.

Please close this issue if you have no further questions about the code itself. For more generic solution architecture questions you can reach out to your AWS technical account management team.

**Comment by disa6302** [comment]
Closing based on tag
