### ISSUE TITLE
Question: Is it possible to get an HLS streaming session URL from a WebRTC stream?

### ISSUE THREAD

**Issue by awriley** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#107]
I am developing a React Native mobile application and I am trying to find a way to stream video from a mobile device's camera so that it can be consumed by a third-party via an HLS endpoint. I also would like to be able to save the media for later playback.

By combining the react-native-webrtc module with the examples provided here, I was able to set up a WebRTC stream to a KVS signaling channel and view a video feed in the AWS console. However, I'd like to take this a step further, if possible. I'd like to create a direct link to this stream for real-time playback in a video player in a third party application. I'm thinking I may have misunderstood the functionality of Kinesis Video Streams. Is it possible to take that WebRTC stream and somehow convert it to an HLS stream, or are those two distinct use cases for Kinesis Video Streams without overlap? I've seen other paid services that list this capability, but I'd much rather leverage AWS for this if possible.

**Comment by MushMal** [comment]
Currently, there is no way to achieve this out of the box. You might want to either end up with dual-streaming from the device (KVS stream + KVS webRtc) or have a client that does webrtc with the device and it turn produces KVS stream for HLS and persistence

**Comment by awriley** [comment]
> Currently, there is no way to achieve this out of the box. You might want to either end up with dual-streaming from the device (KVS stream + KVS webRtc) or have a client that does webrtc with the device and it turn produces KVS stream for HLS and persistence

Ok, thank you for the quick reply. I'll keep looking.
