### ISSUE TITLE
Secure channels with Cognito identity pool

### ISSUE THREAD

**Issue by purbanow** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#108]
Hi

I'm building video chat using Cognito + webRTC and I'm trying to figure out how to secure access to dynamically created channels so every user will be only able to access particular rooms.

Thanks a lot!

**Comment by MushMal** [comment]
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#managing-credentials

Resolving
