### ISSUE TITLE
FIrefox version 83 causing (Offer and answer have different number of m-lines (2 vs 1))

### ISSUE THREAD

**Issue by TonyKim0627** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#109]
Hello team, we have a setup of master running on c sdk, and viewer running on browser using javascript sdk.
When we were using Firefox 78.4.1esr we were able to successfully make stable connection between master and viewer.
After the browser update to version 82.0/83.0, we get the following error:

Offer and answer have different number of m-lines (2 vs 1).
This is preventing the browser from even making connection to ICE server.

Any insights would be appreciated.

Thank you.

**Comment by disa6302** [comment]
Closing because this is related to C SDK
