### ISSUE TITLE
Does this SDK have a plan to support N:N connection?

### ISSUE THREAD

**Issue by sdkim81** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#110]
AFAIK, this sdk only support 1:N (Master and Viewer) connection but is there any plan to support N:N connection?

**Comment by MushMal** [comment]
There are two parts to your question.

1) Whether the signaling supports N:N - aka Full Mesh
2) Whether there is a support for SFU type of scenario

We are contemplating on both but no yet ETA on the decision making.
