### ISSUE TITLE
Unable to retrieve getStats data

### ISSUE THREAD

**Issue by JESii** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#111]
We're using the example app to learn about and test the WebRTC capabilities of Kinesis. We are able to run a master and viewer successfully; however, we are unable to get statistics data using the `onStatsReport` callback that is included in the app.

Examining the payload following the `getStats` call, we only see a `size` value -- nothing more. We added the error test to ensure that we were getting a "successful" result.

![image](https://user-images.githubusercontent.com/486/102788029-ded9db80-4356-11eb-8dbb-215b6d47f2f2.png)

Please let me know what we need to do to get a complete statistics report. Thanks.

**Comment by MushMal** [comment]
I am not sure why the browsers WebRTC peer connection is not returning stats. Perhaps this is a good question to ask the browsers WebRTC manufacturer? Does this repro on Chrome? FireFox, etc? More data will help other customers to respond

**Comment by MushMal** [comment]
Resolving as stale due to no responses

**Comment by JESii** [comment]
Tested only on Chrome; tested multiple times over the last month with other members of the team.

Not sure who to contact for the “browser’s WeebRTC manufacturer”?

We can test this out on Firefox and see what happens there.

Thanks…jon
