### ISSUE TITLE
only working when using localhost:3001 but cannot use ip like 192.168.x.x:3001

### ISSUE THREAD

**Issue by anson1788** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#116]
-webpack.dev.config.js
<img width="447" alt="螢幕截圖 2021-02-03 上午9 47 39" src="https://user-images.githubusercontent.com/23080221/106686174-dedf2380-6604-11eb-91b7-00b623b04818.png">
i added  host: '0.0.0.0' in webpack.dev.config.js
and then try to call the test page using ip (like 192.168.x.x:3001)
while connecting to the signal client, it returns error
<img width="759" alt="螢幕截圖 2021-02-03 上午9 49 39" src="https://user-images.githubusercontent.com/23080221/106686407-31204480-6605-11eb-90bb-c6c393d4c424.png">

do anyone experiencing a similar problem?

**Comment by anson1788** [comment]
dont know why but when i run npm run release , everything is working

**Comment by mukesh-2538** [comment]
Yes i am also experiencing the same problem.

**Comment by sirknightj** [comment]
Hey @anson1788, can you try the latest and also visit your browser's debug console and see what it prints out?

**Comment by sirknightj** [comment]
Closing due to no response.

If the error is related to `getUserMedia`, please refer to the documentation: https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia
