### ISSUE TITLE
How to run the test webpage in Local network?

### ISSUE THREAD

**Issue by mukesh-2538** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#117]
I am receiving 
**[2021-02-10T13:44:39.907Z] [ERROR] [MASTER] Signaling client error**
After adding host 0.0.0.0 to access the webpack.dev.config.js.

On localhost it is working perfectly.
`
**Changes made:**
 devServer: {

        contentBase: path.join(__dirname, 'examples'),

        publicPath: '/',

        host: '0.0.0.0',

        port: 3001,

        disableHostCheck: true,

    }
`
How is the KVS test page hosted over the internet ? 
https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html

what changes should i make to access the page from other pc Browsers within the same network?

**Comment by disa6302** [comment]
We publish our page using github pages option.
