### ISSUE TITLE
Connect to KVS stream from AWS Connect as Viewer for live monitoring

### ISSUE THREAD

**Issue by laamlatay** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#131]
I have setup a contactflow in AWS connect with live streaming block that creates KVS stream from customer audio. I want to connect to that stream as WebRTC Viewer but there is not signaling channel at this point in KVS, only a stream.
Is it possible to connect to that stream without signaling channel or can we somehow associate that stream with a signlaing channel?

**Comment by disa6302** [comment]
Your set up is unclear. You have to create a signaling channel to use webrtc. It can be the same name as the stream.
