### ISSUE TITLE
[QUESTION] recommended way to manage credentials from browser?

### ISSUE THREAD

**Issue by cesarpachon** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#14]
hi, I am starting to work with kinesis video stream to implement a two-users videoconference web app. my question is: what is the recommended way to manage the credentials? I suppose you don't want to expose any secret key to the browser. my options are: 
- 1. use the secret keys in server side (i.e.: lambda + API gateway) to initialize object there and return to the browser. but I suspect the object is a live thing, not just some json that I can serialize to the client. 
- 2. somehow provide temporal, one-time-use, credentials? 
thanks!

**Comment by petscheit** [comment]
I would be interested in this as well!

**Comment by timetxt** [comment]
+1

**Comment by moranji** [comment]
+1

**Comment by MixMasterMitch** [comment]
I have added a new section to the README that can help provide some additional guidance: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/tree/managing-credentials#managing-credentials

**Comment by MixMasterMitch** [comment]
Closing as documentation around this has been added to the README.
