### ISSUE TITLE
is this still usable?

### ISSUE THREAD

**Issue by bgunner** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#144]
Please, is this sdk still usable? 
2 years without any addition... I'm trying to create an app with live streaming and I'm not being able to do it. Many errors happening, even when copying/pasting the sample tutorial and I'm not being able to know if there is anything wrong with my code or if it's a problem with the sdk (2 years on a new technology as webrtc is an eternity).

Also I thought about starting with the sdk v3 to verify if the errors stop but there's no enough documentation on that. I'm really lost. Please, is this still safe for a production usage?

**Comment by disa6302** [comment]
@bgunner , 

The test page works fine. What is the issue that you are facing? Please include logs of errors. 
This ticket lacks any detail for any productive debugging.

**Comment by jdelapla** [comment]
@bgunner Also, as for your concerns about 2 years without any updates, this JS version of the SDK is using an API from our C based SDK https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c which has new released every quarter.
