### ISSUE TITLE
[Question] Does this support AWS Kinesis Video Signalling Client for Javascript v3

### ISSUE THREAD

**Issue by tejaschandra911** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#153]
Hi,

We are working on migrating from AWS Kinesis Video Signalling Client v2 to v3, and we are noticing issues with this version of WebRTC SDK such as viewer not getting any video etc., I tried looking online for a WebRTC SDK version which could support v3 but, could not find any.

Could you confirm whether, this SDK can work with v3?

**Comment by disa6302** [comment]
@tejaschandra911 , 

I would recommend using what our SDK is tested with (https://github.com/aws/aws-sdk-js). I am still unclear on the changes between the 2 versions, but we do not have a version that is tested with v3 today.

**Comment by tejaschandra911** [comment]
@disa6302 We have managed to migrate to v3 version in November. The issues were mostly due to webpack. Now, it has been resolved.
