### ISSUE TITLE
How to measure per frame latency?

### ISSUE THREAD

**Issue by utsavrai** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#155]
I want to measure the video latency over the webrtc

**Comment by disa6302** [comment]
@utsavrai , 

Unfortunately, there is no straightforward way to do this. Perhaps, this can be a useful resource:

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/687#issuecomment-669274565
