### ISSUE TITLE
How to store/save the video at AWS S3 with AWS KVS Signaling channel?

### ISSUE THREAD

**Issue by nishitchittora** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#156]
I'm currently developing a web application in ReactJS, where a user can record a session with his webcam and stream it to AWS infra. I have come across Amazon Kinesis Video Streams with WebRTC [npm module](https://www.npmjs.com/package/amazon-kinesis-video-streams-webrtc). Whereby creating SignalingChannel a user can stream that data to AWS master and viewer model.

But I want to store that session of a user in some persistent storage like AWS S3. So that the session can be reviewed later by the reviewer.

Wanted to know if I'm correct for using AWS KVS? what will be the possible steps to store the video on S3?

**Comment by dangolbeeker** [comment]
IVS may fit your use case better. 
https://aws.amazon.com/blogs/media/build-a-live-streaming-app-with-user-generated-content-in-less-than-an-hour-with-amazon-ivs/

* I do not work for AWS

**Comment by nishitchittora** [comment]
@dangolbeeker Thanks for reply!!

**Comment by disa6302** [comment]
@nishitchittora , 

WebRTC is a peer-peer communication, which means our SDK does not have inbuilt support to save the video in AWS S3 buckets. 
This article is useful in determining the right tech for your use case: https://aws.amazon.com/blogs/iot/choose-the-right-aws-video-service-for-your-use-case/
