### ISSUE TITLE
addTrack call from client not detected by master's "track" event listener

### ISSUE THREAD

**Issue by life-efficient** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#16]
I have a RTCPeerConnection set up which is working between multiple devices (for streaming the audio, webcam and screen). However, when I add a new track to the peerConnection from a viewer, it's not detected by the master (looking at chrome://webrtc-internals/). I can see that chrome://webrtc-internals/ detects the tranceiverAdded event for the viewer, but nothing is detected by the master.

**Comment by life-efficient** [comment]
Upon opening the signaling channel from the viewer's code I add the local stream to the peer connection, the master detects that this track was added. However if later, as a viewer, I remove a track, and then try to add it again again (e.g. toggle screenshare) then the add track event is not detected by the master. Similarly if I want to send a stream from one viewer to another via the master (star network topology style), the stream added by the master is not detected by the intended recipient viewer.

**Comment by rafael-cruz-cloudpix** [comment]
Hi, 
do you have any news about this?

**Comment by life-efficient** [comment]
You need to make sure the peers have negotiated. 

Send SDP offer and get SDP answer from remote peer to ensure that each peer has the correct remote and local session description. This session description contains the new streams (containing new tracks) that may have been added and hence triggers the "track" event.

Here's a link that explains how to do negotiation: https://blog.mozilla.org/webrtc/perfect-negotiation-in-webrtc/
