### ISSUE TITLE
SignalingClient master disconnects quite soon from WSS endpoint

### ISSUE THREAD

**Issue by Snapu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#164]
SignalingClient master disconnects quite soon from WSS endpoint after a few minutes. I can reconnect until the credentials finally expire and then have to reinitialize everything.

Are there any better ways for me to handle that? If I am not the only one with this issue, could we build it in to the lib?

**Comment by sirknightj** [comment]
Refer to #218.
