### ISSUE TITLE
Multiple Viewer of different Master(Channel) From One Browser Tab

### ISSUE THREAD

**Issue by iRaM-sAgOr** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#169]
Using React JS application, is it possible to  connect as multiple viewer with different channel from one browser tab. I like to know that can we make a browser tab communicate with different master(channel) as multiple viewer at a time.

**Comment by iRaM-sAgOr** [comment]
Yes from same  window. From Same window, Multiple Master will be created with different channel, and from one browser tab, different instance will be created to join with different channel(Master). Is it possible?

**Comment by disa6302** [comment]
It should be possible if you are able to model the application that way. If you face issues while doing this, do reach out and the team can take a look.
