### ISSUE TITLE
IAM policy and security

### ISSUE THREAD

**Issue by bangersandflash** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#17]
Can you please tell me which policies I need to apply to the IAM and if it's the same policies for VIEWER and MASTER roles?

Also, what is the recommended approach for best practice security? Should I be generating a temporary IAM user each time the client is loaded? It doesn't seem secure to have the key/secret visible in the client-side code?

**Comment by MixMasterMitch** [comment]
The IAM policy of the credentials used must allow the `kinesisvideo:ConnectAsViewer` and/or `kinesisvideo:ConnectAsMaster` action for the signaling channel resource.

Yes, best practice is to create temporary credentials with least privilege. See either STS or Cognito for how to get temporary credentials.

**Comment by MixMasterMitch** [comment]
I have added a section to the README about this: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#managing-credentials
