### ISSUE TITLE
Failed to parse source map from

### ISSUE THREAD

**Issue by juanea** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#172]
When running a react application with react-scripts start, I am getting this error Failed to parse source map from.

![image](https://user-images.githubusercontent.com/9869942/171193624-920d3e9e-a047-4a7e-8d69-a6edee01624c.png)

In one of the comments in this post, there is a suggestion that the issue might be not tracking src directory in the npm package with the 
files in packe.json for a typescript library which has a compilation step.

https://github.com/facebook/create-react-app/discussions/11767

**Comment by niyatim23** [comment]
Hi @juanea, can you please try out the latest release 2.0.0 and see if the issue still persists?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to open an new issue in case of a problem / questions

**Comment by osehmathias** [comment]
I am using the latest release in Node 20 and Node 19 and this issue persists.
