### ISSUE TITLE
Recent issues specific to Safari: Viewer can't see Master's video

### ISSUE THREAD

**Issue by behnam354** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#174]
Hi, 

We've been successfully running this sdk as well as the [KVS WebRTC Test Page](https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html) using safari and other browsers. However, it's been a couple of days that we noticed that we are having issues specific to Safari (Chrome is working fine) and the viewer can't see the video of the master. We tried using two separate safari windows on the same laptop or different laptops and in all cases the viewer can't see the master's feed. (I don't have a solid statement on how the audio works, it seems that the audio sometimes goes through and sometimes doesn't)

I've shared some screenshots and logs. The screenshots show the two-way video works on chrome but not on Safari. On Safari, only viewer (sometimes) might be able to send the video and if the viewer doesn't send video, then both master/viewer players will show black screens when using the KVS Webrtc test page. Logs and screenshots are attached: [logs_screenshots.zip](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/files/8923288/logs_screenshots.zip)

We appreciate it if you have any thoughts on this.

System settings of my laptop (we tried it on other laptops and they all had similar issues):
- macOS Big Sur 11.2.3, Apple M1
- Safari Version 14.0.3 
- Chrome Version 97.0.4692.

Best,
Behnam

**Comment by disa6302** [comment]
Was there a safari version update between the working and non-working case?
Also, what is the master running? Do you see any errors on the master end?

**Comment by behnam354** [comment]
Thanks for getting back to me.

1. There wasn't a safari update between these two cases. 
My safari version has been on 14.0.3 (16610.4.3.1.7) for a while and recently the demo page has stopped working. We also see the same issue with Safari 15.5 (17613.2.7.1.8) and 15.4 (17613.1.17.1.13) on my colleagues' laptops.
[P.S. I'm not sure if that's related or not but we've been seeing similar issues on chrome (when hardware acceleration was on and I believe chrome came up with a fix for that). There were no issues with safari at that time.]

2. The master is running on Safari as well. So I opened up two of your demo pages on different safari windows (same laptop or different laptops) and I wasn't able to send video from master to viewer which was doable in case of a chrome browser. There are no errors in master/viewer logs. The logs are all attached in the .zip file that I attached to my original post.

**Comment by disa6302** [comment]
I checked the logs, but did not see anything standout. Is the same webcam the source of input for the master and the viewer?

**Comment by behnam354** [comment]
Thanks for checking the logs. We ran multiple experiments: one using the same webcam (same laptop) for running the master and the viewer and the other experiment we used was different webcams (laptops) were used for the master and the viewer and in both cases we faced issues with safari (but not with chrome)

**Comment by behnam354** [comment]
Hey there, I was wondering if you've had a chance to look into this issue and if you have any updates on this?

**Comment by disa6302** [comment]
@behnam354 ,

Apologies for the delay. Have not had the chance to look at this issue. Did you see this issue on any Mac laptops before M1?

**Comment by hassanctech** [comment]
Also it looks like Chrome Master and Safari Viewer works fine and Chrome viewer and Safari master works fine... it's only the Safari master + Safari viewer combination that isn't working.

**Comment by hassanctech** [comment]
I just tried it with Safari Technology Preview from Apple's site, this one [https://secure-appldnld.apple.com/STP/012-32918-20220629-B3452905-0138-4CA9-A4E6-334B63585653/SafariTechnologyPreview.dmg] and it works just fine with that!!

**Comment by hassanctech** [comment]
My best guess at this time is something broke in Safari and since Safari updates are tied to MacOS updates perhaps somewhere in the middle when it stopped working for you MacOS had an update that updated Safari that caused this issue.  It doesn't appear to be broken in their latest preview.  To try Safari 16 (beta or via the technology preview) you do need to be on MacOS 12.3 or later.

Finally, looking at the release notes there do appear to be a ton of changes they've made to enhance the webrtc experience here:  https://developer.apple.com/safari/technology-preview/release-notes/

**Comment by behnam354** [comment]
Thanks for looking into this! Do you think this repo can be updated so that it could bypass the issue that safari has raised? Or does it mean that this sdk won't work on safari 14/15 versions? If you think there is no way to fix the safari issue for certain versions, it would be nice to list the broken versions in the readme so that other people are aware as well. We've already tested the demo page on safari versions 14.0.3, 15.4, and 15.5 and none of them work. Thanks!

**Comment by behnam354** [comment]
We've tried a few combinations of browsers to give you more data on broken versions .. We still see issues when testing Safari 16 as one end and Safari 14.0.3 (or Chrome 97.0.4692.99) as the other end. 

Here is the summary of our observations: 

| Master               | Viewer               | Video Works | Audio Works                       | Notes                                                                                                                        |
|----------------------|----------------------|-------------|-----------------------------------|------------------------------------------------------------------------------------------------------------------------------|
| Safari 15.5          | Safari 14.0.3        | Yes         | Yes                               | ✅                                                                                                                            |
| Safari 16            | Safari 14.0.3        | No          | Yes                               | 16.0 (Master) video gets frozen. Sometimes viewer gets no stream                                                             |
| Chrome 103.0.5060.53 | Safari 14.0.3        | Yes         | Yes                               | ✅                                                                                                                            |
| Safari 14.0.3        | Safari 15.5          | Yes         | Yes                               | A little lag upon initial connection, no problems after 10s                                                                  |
| Safari 14.0.3        | Safari 16            | No          | Yes but from master is very quiet |                                                                                                                              |
| Safari 14.0.3        | Chrome 103.0.5060.53 | Yes         | Yes                               | ✅                                                                                                                            |
| Safari 16            | Chrome 97.0.4692.99  | No          | No                                | Neither participant can see/hear the other. 16.0 (Master) cannot see own video. Video Players indicate no connection occured |
| Chrome 103.0.5060.53 | Chrome 97.0.4692.99  | Yes         | Yes                               | ✅                                                                                                                            |
| Chrome 97.0.4692.99  | Chrome 103.0.5060.53 | Yes         | Yes                               | ✅                                                                                                                            |

Please let us know if you have any updates!

**Comment by disa6302** [comment]
Thank you for this. From the table, I see Safari 16 is not working for you. As suggested by @hassanctech , is the Safari 16 you are using beta/ running technical preview?

**Comment by behnam354** [comment]
Yes the Safari 16 was the latest Tech Preview.

**Comment by disa6302** [comment]
@behnam354 , 

As per your matrix, everything seems to be working fine with Safari versions lower than 16. I tested on my end with different browser combinations using Safari 15.6 and everything works fine. At this point, using a lower Safari version would be the fix.

**Comment by jdelapla** [comment]
As the only issue is with Safari 16, and Safari 16 is still in beta I will close this ticket and we'll review Safari 16 once it's formally released.

**Comment by jeryini** [comment]
Is Safari 16 still an issue? We've reports of some users experiencing issue (video not working) with Safari as viewers on iOS devices, specifically iPhone.

**Comment by sirknightj** [comment]
@jeryini I am using Chrome 113.0.5672.126 (master) along with Safari 16.4 (viewer) on my Mac am able to send/receive video on both ends.

Please create a new issue with some logs to investigate further.

**Comment by punittttt** [comment]
> @jeryini I am using Chrome 113.0.5672.126 (master) along with Safari 16.4 (viewer) on my Mac am able to send/receive video on both ends.
> 
> Please create a new issue with some logs to investigate further.

@sirknightj  how did you manage to run it on safari IOS? I am trying to run it on react-native-webview on ios using safari but no video is coming in the SDP offer/answer only audio

**Comment by sirknightj** [comment]
> @sirknightj how did you manage to run it on safari IOS?
Using the browser. Tried it on an iPhone SE and MacBook Pro.

What are you using as the master? Is the master sending video?

**Comment by punittttt** [comment]
@sirknightj i am using https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html as a master and master is sending the video, it is working fine on android.  
<img width="1004" alt="Screenshot 2024-11-05 at 18 00 12" src="https://github.com/user-attachments/assets/ef6dd094-fe18-4859-a5e8-7768278af10b"> When i try to run it on safari it gives me this error.

**Comment by sirknightj** [comment]
Does https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html as a viewer work for you?

I just tried that page with Chrome on android as master, and safari on iOS as viewer, and I can see both video feeds and hear both audio feeds.

<img width="407" alt="image" src="https://github.com/user-attachments/assets/0e0a4a9f-9a19-4785-a150-c315b8a4ce4b">

**Comment by punittttt** [comment]
yes this https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html actually works on both android and IOS but my goal is to run the media playback shown in the screenshot above which is not supported by ios
