### ISSUE TITLE
KVS WebRTC streaming and remote recording on the server error: moov atom not found Invalid data found when processing input video

### ISSUE THREAD

**Issue by gharbit** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#192]
Hello,

Master: Raspberry Pi 4, KVS WebRTC SDK C 1.7.3
Viewer: Angular WebApp based on SDK JS example. The backend is a NodeJS app running on EC2 instance.

We stream webRTC video for displaying on the web navigator. Simultaneously, we stream via UDP to our server (EC2) to record a copy of the video.
The master pipeline is : 
`-e autovideosrc ! queue ! videoconvert ! videorate ! video/x-raw ! \ x264enc bframes=0 speed-preset=veryfast byte-stream=TRUE tune=zerolatency ! \ video/x-h264,stream-format=byte-stream,alignment=au,profile=baseline ! tee name=t ! queue leaky=1 ! \ appsink sync=TRUE emit-signals=TRUE name=appsink-video t. ! queue leaky=1 ! filesink location= file.mkv t. ! queue leaky=1 ! h264parse ! rtph264pay pt=96 ! udpsink port=5080 host=10.8.0.1`
     
We receive and record the stream in the backend through gst-launch app with the following args:
`function getGstPipelineArguments(url) { 
var args = ['--eos-on-shutdown', 'udpsrc', uri=udp://10.8.0.1:5080, '!', 'application/x-rtp, media=(string)video, clock-rate=(int)90000, encoding-name=(string)H264, payload=(int)96', '!', 'rtph264depay', '!', 'h264parse', '!', 'mp4mux', '!', 'filesink', location=${url}, '-e' ]; 
return args; 
}`

When the stream is ended, the video is registred on the server but it's corrupted. we have the following error when trying to replay the video : `moov atom not found Invalid data found when processing input`

Actually, the error is related to an incorrect end of stream on shutdown from the master. We added the related flag (`--eos-on-shutdown`) in the gst-launch command but still have the same issue.

Any solution?

**Comment by sharadrj** [comment]
gharbit, unfortunately we are unable to help with gstreamer pipeline or plugin issues. Suggest seeking help in gstreamer related forums.
