### ISSUE TITLE
Add NodeJS or Express server example too . in which master stream can be invoked from nodejs server with help of openCV

### ISSUE THREAD

**Issue by Ramnirmal0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#193]
Is it possible to add a NodeJS / serverside script example too? in which the master stream can be served from an API call. with help of the OpenCV library, webcams can be triggered since navigator() won't work on the server side.

**Comment by disa6302** [comment]
@Ramnirmal0 , 

We will take this in as an enhancement item and evaluate. Thank you
