### ISSUE TITLE
Master does not receive sdpOffer event sometimes, even though KVS signaling client is open

### ISSUE THREAD

**Issue by vishalkb** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#195]
Master does not receive sdpOffer event sometimes, even though KVS signaling client is open

1) start the viewer as per the aws samples viewer.js code
2) start the master as per the aws samples master.js code
3) Viewer send the offer using signaling client offer, master received the sdp offer and master sent sdpAnswer herefater
viewer received the answer and after ICE is connected post successful candidate pair selection after ice gathering, both the viewer and
master peer is connected and successfully media stream is flowing
4) Stop the viewer and master
5) again repeat the same step 1) to 4) in the same mobile device multiple times
6) sometimes in step 3) sdp offer is sent from viewer but master does not receive the sdpOffer event and connection didnt able to establish as no sdp answer  is received by the viewer

**Comment by niyatim23** [comment]
Hi @vishalkb, can you please share logs (master and viewer) demonstrating this issue?

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to open an new issue in case of a problem / questions
