### ISSUE TITLE
data channel is broken after sometime after sending few bytes of data from viewer to master

### ISSUE THREAD

**Issue by vishalkb** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#196]
1) In few devices data channel is broken after sometime after sending few bytes of data from viewer to master and then after few secs peer connection or ice connection state is in disconnected state, thus blocking the peer communication and the use has to drop the call

**Comment by niyatim23** [comment]
Hi @vishalkb, what are you using as a master and as a viewer? Can you please share logs from both sides to understand what is going wrong

**Comment by niyatim23** [comment]
Closing due to no response. Feel free to open an new issue in case of a problem / questions
