### ISSUE TITLE
Is it possible to start Master with Nodejs without Browser ?

### ISSUE THREAD

**Issue by Ramnirmal0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#197]
**Requirement (workflow):**

viewer UI (React) -> start service -> POST request with channel Name -> start remote master webcam using nodejs (without browser) -> start viewer  -> display stream in viewer UI

**key challenges:**

1. when the Master code (from example) is started using Nodejs .signaling channel is opened. but the viewer is not recognizing the master / no data is streaming in the viewer end/connection with the master-viewer is not getting established. why?

2. since Navigator API is browser API, I am using the OpenCV library to start the webcam in Master END. if I am using OpenCV does it require any additional code changes in SDK? 

Is it possible to start Master with Nodejs without Browser?  if No, is there any alternative I can try to achieve the same using WebRTC?

**Comment by niyatim23** [comment]
Hi @Ramnirmal0, have you tried using the WebRTC C SDK as master?

**Comment by Ramnirmal0** [comment]
@niyatim23 Closing this ticket . Explored WebRTC C SDK as master

FOR THE DOCUMENTATION PURPOSE , if anyone have same question

Explore WebRTC C producer library : https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c
 build and run ./kvsWebrtcClientMasterGstSample and update the pipeline code using GStreamer will start the webcam and send stream to signalling channel . run shell command in node on API request. 

Explore about Gstreamer here : https://www.youtube.com/watch?v=VLxAkmi9K-M&t=2296s

Instead of Raspberry pi you can do setup for local machine also explore : https://www.youtube.com/watch?v=9YI4POQVUl8&t=2963s

if facing issue in pipeline : https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/1552
