### ISSUE TITLE
Can't get WebRTC Test Page running on my EC2 server?

### ISSUE THREAD

**Issue by mraeclark** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#20]
Seems to npm install just fine. npm run develop launches the server. But I can not connect via my elastic IP port 3001? Security group is set to allow? I know it works because I can use the WebRTC test page.

**Comment by MixMasterMitch** [comment]
I am not sure that I fully understand what you mean when you say "I can use the WebRTC test page." Does that mean you can access it from within the EC2 instance, just not over the EIP?

I am guessing that you need to set the `host` to `0.0.0.0` in the `devServer` config (per [webpack docs](https://webpack.js.org/configuration/dev-server/#devserverhost)) in [webpack.dev.config.js](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/webpack.dev.config.js#L12)

**Comment by mraeclark** [comment]
Yes. Added the host to 0.0.0.0 in the devServer section of webpack.dev.config.js. The webRTC test page comes up but it does not work like my local host version. I'm using the same parameters (key, secret key, and channel name) that functions correctly in my local version.

**Comment by MixMasterMitch** [comment]
Interesting. When you say "it does not work like my local host version", what do you mean? Are there any error logs? If you look in the developer console of the browser are there any clues?

**Comment by mraeclark** [comment]
Thank you. I got it working. My bad, did not understand my chrome browser needed to ignore the certificate request. Needed to set HTTPS:true in the devServer config (per webpack docs) in webpack.dev.config.js
