### ISSUE TITLE
DataChannel from master in example

### ISSUE THREAD

**Issue by kunimasu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#207]
If we want to receive data channel from master, is this correct?

[viewer.peerConnection.ondatachannel = event => {](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/viewer.js#L102)

```
- viewer.peerConnection.ondatachannel = event => {
+ viewer.dataChannel.onmessage = (event: MessageEvent) => {
```

In my case, I received message from master by`viewer.dataChannel.onmessage`.

**Comment by disa6302** [comment]
The sample demonstrates exactly this use case. You would need the onmessage callback to receive from master.
