### ISSUE TITLE
[QUESTION] Why is the Peer role not supported?

### ISSUE THREAD

**Issue by MandarinConLaBarba** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#21]
Why are only `Master` and `Viewer` roles supported? Looking at the documentation, it seems that there should also be a `Peer` role? 

https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-how-it-works.html

Is a "Mesh" topology not supported by KVS?

**Comment by moranji** [comment]
Isn't a Peer a combination of Master and Viewer?

**Comment by moranji** [comment]
> Why are only `Master` and `Viewer` roles supported? Looking at the documentation, it seems that there should also be a `Peer` role?
> 
> https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-how-it-works.html
> 
> Is a "Mesh" topology not supported by KVS?

Isn't a Peer a combination of Master and Viewer?

**Comment by MixMasterMitch** [comment]
`Peer` is not a different role. The `Master` and `Viewer` are peers of each other. 

KVS currently only supports a single `Master`. `Viewer`s are only able to communicate with the `Master` and not other `Viewer`s. This supports use cases where there is a single device (e.g. video doorbell) that one or more clients want to start realtime streaming with.

**Comment by lherman-cs** [comment]
Due to inactivity, I'll close this. Please feel free to reopen it if you need further assistance.
