### ISSUE TITLE
Help with running AWS Kinesis WebRTC and GStreamer

### ISSUE THREAD

**Issue by xtianus79** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#212]
Hi, is this project active and in general release? 

I am trying to utilize this but it is incredibly not well explained and seems to be a preview or alpha release product. 

Is there a place I can get help for this in my platform. I've done IQ and nobody there seems to know how to utilize it either.

**Comment by hassanctech** [comment]
@xtianus79 Please see here to learn more about AWS Kinesis Video Streams WebRTC, there you will find details about how to use this offering and the various SDKs that are provided:  https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/what-is-kvswebrtc.html

This is a general release offering.

We provide samples integrating GStreamer with our WebRTC offering in our C SDK, you can find them here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/master/samples

I'm closing this ticket as there is not a specific question here, if you have a specific question please open a new ticket with details.
