### ISSUE TITLE
How can I grab the frames after it reaches the viewer?

### ISSUE THREAD

**Issue by sumitmandal13** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#240]
Is there any way where I can grab the frames, after it reaches to the viewer? Imagine a scenario where I want to check how many times a person blinked on the live stream call. For that I may be needing frames from the viewers browser processes it and send the ouput back to the viewer. 
![master-viewer](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/assets/122588883/6532c1af-e23b-4bba-814a-329d78e8c973)
Take a look at this architecture, where there are multiple producer/master that are generating the streams and are passing the streams to lets say one lambda or viewer. From there I want to process the frame using opencv. How can I achieve this?

**Comment by sirknightj** [comment]
Hi @sumitmandal13,

Please reach out to aws support so we can connect you with specialists to help support your use case and onboarding to Kinesis Video Streams/WebRTC.
