### ISSUE TITLE
Latest release breaks example on github pages

### ISSUE THREAD

**Issue by RaviVadera** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#256]
Following same process as previously to be able to test kinesis webrtc stream on example page deployed at https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html does not work.

The credentials used already has IAM policy AmazonKinesisVideoStreamsFullAccess attached.

The stream fails with following line on log,
[2023-08-21T10:57:40.093Z] [ERROR] [VIEWER] Encountered error starting: {
  "message": "The account id xxxxxxxxxxxxxxxxxx is not allowed to access the resources",
  "code": "AccessDeniedException",
  "time": "2023-08-21T10:57:40.092Z",
  "requestId": "xxxxxxxxxxxxxxxxxx",
  "statusCode": 403,
  "retryable": false,
  "retryDelay": 87.08014669943952
}

Able to produce locally when running through ```npm run develop```
Previous release seems to be working with same setup locally.

**Comment by sirknightj** [comment]
Hi @RaviVadera, please help us with the following:
1. Is the signaling channel you are trying to connect to configured for WebRTC ingestion? This is currently only available in us-west-2, so please unconfigure it if so.
2. If not, could you please share the options used when running the sample?

**Comment by sirknightj** [comment]
We're looking into this and will update ASAP.
