### ISSUE TITLE
Viewer hitting signaling client error and not recoverable

### ISSUE THREAD

**Issue by chenhudl** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#262]
We have a one producer to many viewers setup.
During our stress testing for viewer connection, we hit a signaling client error and we are unable to recover from that.
Producer is still able to connect to the signaling channel, but the viewers continue to hit this error ever since.

We assume that there is some kind of limit for viewers but we're not certain what is happening.

- What could be the reason for this?
- What would be a proper way to remove this state of signaling channel? 
- Should we update or delete the channel?

![Screenshot from 2023-09-11 13-03-17](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/assets/109285834/0a2315ec-fd1a-4e90-b791-d29d0e0275d1)

![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/assets/109285834/ffaf7c16-649e-4aa8-9151-6be6a5b859c9)

**Comment by chenhudl** [comment]
This seems to be recovered automatically after two hours? but we're not sure how it happened 
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/assets/109285834/08ef9bc7-0669-4cb2-b23b-695272cbd277)

**Comment by disa6302** [comment]
@chenhudl , 

The screenshots are cut so it is not clear what the error is. But there is a limit on the number of viewers that can be connected to a channel at a time and it is set to 10 (https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-limits.html#limits-signaling-service).
