### ISSUE TITLE
Peer connection from Web client to EC2

### ISSUE THREAD

**Issue by marcfielding1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#27]
Hey Guys,

So I was talking to AWS support and thought I'd ask here before I raised another case.

I have a use case for this where we want to stream videos from our offices(from various devices) where we're taking 20 second videos of an object, now the client example is perfect for what we want.

The bit I'm struggling with is deciphering how I p2p from an EC2 instance to the client - the reason I want to do this is that we want to split the stream into frames and then output them to s3, which in turn will go to Ground Truth for labelling.

I'm aware there are Java clients for KVS but we're a JS house so I'd rather not have some random Java knocking about - could you point me to any reading that can help solve this? Thanks for any help in advance, I work with AWS daily but never with KVS so it's proving a bit of a head spinner :-)

**Comment by MixMasterMitch** [comment]
What are you trying to achieve? Is it as simple as streaming 20 second videos from devices in the office and publishing them to S3 + Ground Truth?

Are you also trying to do realtime video playback on another device? In other words, is there a particular reason to use WebRTC?

What kind of devices are you using? Mobile devices? Webcams?

**Comment by marcfielding1** [comment]
Heya, so the reason I wanna use webrtc is it's easy to implement on everything from react, browser to smart glasses.

Also the second use is when someone wants to order stuff from us they can point their smartphone at it and then we hook the stream up via KVS to Sagemaker so it's kinda of 1 tech thing.

The 20 second videos are from our shop take on teams, so they go into a shop, put all their stock into our booths video it for 20 seconds each at which point we need those videos to be split into frames and labelled.

**Comment by marcfielding1** [comment]
Ahh hold up I don't actually need to try and get the stream in node, I wonder if I could just launch a gstreamer process and save it to a file. I shall investigate.

**Comment by marcfielding1** [comment]
Hey I'm going to close this as there's an easier way with Lambda Layers and an S3 trigger. Apologies for any inconvenience caused!
