### ISSUE TITLE
Problems getting sdk to work with React

### ISSUE THREAD

**Issue by supertick** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#282]
Sadly, it looks like there is no straight forward examples of using it in any propular js framework.
I got the included webrtc example's page to work - although it seems a little problematic in that a viewer cannot reconnect ?
Trying to get it incorporated into a react after installing the npms
I get 
![image](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/assets/1266144/807d4bae-82fe-4911-ad31-ed38b028c553)
Looking into the node_module its using "process" which wouldn't be appropriate for a browser only nodejs.

I've gotten webrtc working before in a react app, but trying to follow this sdk's instructions seems "challenging"
Is there a simple, minimal example of how to get a viewer working in a react app ?
(Hopefully, your not going to refer me to some buried example in issues that a outside contributor made)
Thanks in advance.

**Comment by sirknightj** [comment]
Please see the linked pull request, which is a sample implementation of this repository in the popular JS framework: React.JS.
