### ISSUE TITLE
Does this SDK support ios webview?

### ISSUE THREAD

**Issue by TE-0000139074** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#285]
This SDK supports Android webview as described in the compatibility section of the README, but what about ios WebView?

**Comment by stefankiesz** [comment]
Hi, do you mean ios' WKWebView?

**Comment by TE-0000139074** [comment]
Yes, I would like to know whether the WKWebView works which is one of the method to realize WebView. And I would also like to know for the SFSafariViewController.


SFSafariViewController

**Comment by niyatim23** [comment]
Hi, we have tested our sample application on Apple devices in the past and seen no issues but we cannot help you with the custom integration with Apple's WebViews
