### ISSUE TITLE
Using Safari 17.1.2 on macOS, master video isn't ingested on KVS

### ISSUE THREAD

**Issue by redvivi** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#289]
No media is available on the media playback.

I guess direct media ingestion from Safari isn't supported?

**Comment by sirknightj** [comment]
Correct. Currently, Chrome is the only supported browser for WebRTC ingestion.

https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/ingest-media.html
https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/releases/tag/v2.2.0

**Comment by redvivi** [comment]
Thanks @sirknightj - any insight on the roadmap?

**Comment by BenOmerDev** [comment]
Hi @redvivi, would you please share with us your use case with Safari? While we don't have specific roadmap insights to share, a complete understanding of desired use cases helps us to plan and prioritize.

**Comment by redvivi** [comment]
Thanks @BenOmerDev .

The use-case is to support video stream ingestion from a web app Safari/iOS to then connect to various AWS Rekognition Video processing services.
Detect / compare faces, label objects...

**Comment by punittttt** [comment]
> Hi @redvivi, would you please share with us your use case with Safari? While we don't have specific roadmap insights to share, a complete understanding of desired use cases helps us to plan and prioritize.

Hey @BenOmerDev  , do we have something for safari yet? i am trying to stream remote video from a doorbell into the ios devices using react-native-webview , which is not working working.
