### ISSUE TITLE
What is the best way to clone, install and run this remotely on AWS?

### ISSUE THREAD

**Issue by francisdavidoconnor2017** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#29]
Hi, this is an excellent example and I am fine running it on my local machine. 

I would like to set it up myself remotely also on AWS. I have tried running a build from S3 but that causes a security issue on the web cam access. I am now attempting to clone into an EC2 instance and run dev from there, opening port 3001 and using the public url for the instance in my browser, but that just gives me a 'didn't send any response' error. Is there a quick fix for this?

**Comment by MixMasterMitch** [comment]
Try adding `host: '0.0.0.0'` to the `devServer` config: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/webpack.dev.config.js#L12-L16

See Webpack docs: https://webpack.js.org/configuration/dev-server/#devserverhost

**Comment by francisdavidoconnor2017** [comment]
Thanks! All I needed to do in addition was to add disableHostCheck: true to devserver, and it's up and running.
