### ISSUE TITLE
How to add metadata using this library?

### ISSUE THREAD

**Issue by rajeevbbqq** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#294]
I want to add metadata to the stream. Do you have any idea how to do that? 
What I am looking for is according to the Kinesis documentation it is possible to generate autogenerated images to S3. But `AWS_KINESISVIDEO_IMAGE_GENERATION` needs to be added which is not clear using this library.

Document followed: https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/gs-s3Delivery.html#producer-mkv-tags

**Comment by stefankiesz** [comment]
Hi, this library does not support mkv tagging which is supported by our producer libraries. Please refer to our [Producer C](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c), [Producer CPP](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-cpp/tree/master), and [Producer Java](https://github.com/awslabs/amazon-kinesis-video-streams-producer-sdk-java) SDKs. [Here](https://github.com/awslabs/amazon-kinesis-video-streams-producer-c/blob/76a72e9a53291c107e57cc82550f027db2b9e76d/samples/KvsVideoOnlyRealtimeStreamingSample.c#L200) is where metadata is added in a sample Producer C application.
