### ISSUE TITLE
Support for aws-sdk v3

### ISSUE THREAD

**Issue by lkaniak** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#296]
Hello,

will this package support aws-sdk v3 or there are any plans for a migration?

**Comment by sirknightj** [comment]
This SDK itself does not depend on aws-sdk-js. The aws-sdk-js is used in the application layer. There is a sample application in the [demos repo](https://github.com/aws-samples/amazon-kinesis-video-streams-demos/tree/master/webrtc-js) which demonstrates integrating aws-sdk-js v3 with this SDK in the ReactJS framework.

There are currently no plans on migrating to aws-sdk-js v3 on this test page, as v3 does not support a browser script import (which aws-sdk-js v2 provides).

**Comment by sirknightj** [comment]
Hi,

In the latest release (2.4.0), we've compiled the AWS SDK JS v3 packages as a browser script import and are now using v3 for the current sample page. You can refer to the linked PR above and [release notes](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/releases/tag/v2.4.0) for file size changes.
