### ISSUE TITLE
How to access the video/audio data on the WebRTC video call?

### ISSUE THREAD

**Issue by mondor** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#30]
Hi There, I am pretty new to the aws KVS product, and was wondering how we could access the video/audio data that happened during the webrtc call. 

I was able to successfully running this example:  https://awslabs.github.io/amazon-kinesis-video-streams-webrtc-sdk-js/examples/index.html with my colleague.

but when i am going to the "Video Streams" section of the aws console, i couldn't see any available "Media playback". My question is, is the video/audio automatically pushed to the "Video Streams" during the WebRTC call? 

If video/audio are not automatically push (or save) to a "Video Stream", is there a way to enable the pushing of the video/audio data to the Kinesis "Video stream" from within the SDK? or we have to create a server side "Viewer", listen to the video call and push the data to the "Video Stream" manually? (can the browser act as a producer and pushing video to the "Video Stream"?)

I have also read somewhere, in order to pull data down from the "Video Stream", one need to create a consumer, would you be able to point me to the right direction where to find some example for this?

Just give you a little bit of a background, we would like to be able to capture the live video/audio stream from the master via 
Appreciate your help!

**Comment by MixMasterMitch** [comment]
Currently there is no way to have the media in a KVS WebRTC session be published to a KVS Stream directly with the KVS APIs.

However, there are some ways to get media from a WebRTC session to a KVS Stream if you are willing to do some extra work. See the following for some inspiration:
* https://aws.amazon.com/blogs/machine-learning/building-automatic-analysis-of-body-language-to-gauge-attention-and-engagement-using-amazon-kinesis-video-streams-and-amazon-ai-services/
* https://developer.mozilla.org/en-US/docs/Web/API/MediaRecorder

**Comment by tomeraz** [comment]
@MixMasterMitch do you know of any plans to allow kinesis video signaling channel to kinesis video stream conversion?
I want to stream browser webcam through webrtc and eventually play it back from s3

**Comment by MushMal** [comment]
Our JS code is using the browsers existing WebRTC infrastructure. As such we don't control the media API. Per @MixMasterMitch suggestion, you might want to stream into KVS separately.

**Comment by nishitchittora** [comment]
@MushMal @tomeraz  I have a simpler problem statement. I'm using Amazon Kinesis Video Streams WebRTC SDK in the web browser(ReactJS application). Where a user can record a video session which will be one-way communication and I want to save it to s3 for review at a later time.

My Question:
1. Is it possible to do? if yes can you provide some official documentation or way? 

That will be really helpful. Thank you in advance.
