### ISSUE TITLE
How to export example folder?

### ISSUE THREAD

**Issue by overheat** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#316]
A newbie to js.

How to export example folder to another place?
I tried those:
1. `cp -r` 
2. `npm run release`

Both of them got error, after I click on `start viewer` button.
```
[ERROR] [VIEWER] Encountered error starting: @file:///Users/myname/repos/amazon-kinesis-video-streams/webrtc/js/examples/viewer.js:408:36
```

**Comment by overheat** [comment]
I found this in `package.json`
```
"copy-examples-to-dist": "cp -r examples dist",
```

Looks `npm run release` just `cp -r` in the last step.

**Comment by sirknightj** [comment]
Glad you were able to figure it out!

Running `npm run release` will create the following files in the `dist/` folder.
```
kvs-webrtc.js
kvs-webrtc.min.js
```

The sample webpage in the `examples/` directory requires `kvs-webrtc.js` one directory above. You can adjust the path if needed. 

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/de209884fcd388c3fea4937a5b99354ef9519af3/examples/index.html#L412

**Comment by overheat** [comment]
Thanks!
