### ISSUE TITLE
[Enhancements] Consider shipping with a stable version of adapter.js or equivalent

### ISSUE THREAD

**Issue by suggestedfixes** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#34]
The current samples only work best with chrome, and we had very little success testing with other browsers. One of the solutions we found was using adapter.js to improve cross-browser compatibility. We wonder if it is on the roadmap to improve cross-browser compatibility.

**Comment by sharadrj** [comment]
@lherman-cs : good to close this issue?

**Comment by lherman-cs** [comment]
> @lherman-cs : good to close this issue?

Yup
