### ISSUE TITLE
Can master detect when a viewer has connected to channel?

### ISSUE THREAD

**Issue by jiangjunzailushang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#39]
As a master, how do I know if a viewer has entered the channel. Is there a callback method called? In addition, the browser sometimes prompts an error：ICE failed,see about:webrtc for more details。where can I find related solutions

**Comment by MixMasterMitch** [comment]
> As a master, how do I know if a viewer has entered the channel. Is there a callback method called?

No, the master is not notified when a viewer connects to the signaling channel. However, the viewer is expected to send an SDP offer immediately after connecting, so receiving an SDP offer should indicate that a viewer has connected.

> In addition, the browser sometimes prompts an error：ICE failed,see about:webrtc for more details。where can I find related solutions

Can you open another issue to track that? Also can you include the details you have from when the error happens?
