### ISSUE TITLE
About ICE failed question

### ISSUE THREAD

**Issue by jiangjunzailushang** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#40]
Sometimes the code can succeed, sometimes this error occurs. When an error occurs, the master log is as follows, there is no more error information, just ICE failure, please see: webrtc for more details, then the status of iceConnectionState becomes failed.

[MASTER] Channel ARN:  arn:aws:kinesisvideo:ap-northeast-1:421106836067:channel/ZA8781C_VOfb9DwjfY56DisJOICe36wRfrfg3tHkTHVTKj58rSWkbLHdrRVWfvyh/1588839183126
[MASTER] Endpoints:  
Object { WSS: "wss://m-26d02974.kinesisvideo.ap-northeast-1.amazonaws.com", HTTPS: "https://r-2c136a55.kinesisvideo.ap-northeast-1.amazonaws.com" }
[MASTER] ICE servers:  
Array(3) [ {…}, {…}, {…} ]
[MASTER] Starting master connection 
[MASTER] Connected to signaling service
[MASTER] Received SDP offer from client: WebRTCViewer
Using more than two STUN/TURN servers slows down discovery 10.js line 5398 > eval:229
[MASTER] Received remote track from client: WebRTCViewer
[MASTER] Creating SDP answer for client: WebRTCViewer
[MASTER] Sending SDP answer to client: WebRTCViewer
[MASTER] Generating ICE candidates for client: WebRTCViewer
[MASTER] Generated ICE candidate for client: WebRTCViewer
[MASTER] Sending ICE candidate to client: WebRTCViewer
[MASTER] Generated ICE candidate for client: WebRTCViewer
[MASTER] Sending ICE candidate to client: WebRTCViewer 
[MASTER] Received ICE candidate from client: WebRTCViewer 
[MASTER] Generated ICE candidate for client: WebRTCViewer
[MASTER] Sending ICE candidate to client: WebRTCViewer 
[MASTER] Generated ICE candidate for client: WebRTCViewer 
[MASTER] Sending ICE candidate to client: WebRTCViewer 
[MASTER] Received ICE candidate from client: WebRTCViewer
current peerConnection.iceConnectionState = checking 
[MASTER] Generated ICE candidate for client: WebRTCViewer 
[MASTER] Sending ICE candidate to client: WebRTCViewer 
[MASTER] Generated ICE candidate for client: WebRTCViewer 
[MASTER] Sending ICE candidate to client: WebRTCViewer 
[MASTER] All ICE candidates have been generated for client: WebRTCViewer
[MASTER] Received ICE candidate from client: WebRTCViewer 
current peerConnection.iceConnectionState = checking
current peerConnection.iceConnectionState = checking 
current peerConnection.iceConnectionState = checking 
current peerConnection.iceConnectionState = checking 
current peerConnection.iceConnectionState = checking 
current peerConnection.iceConnectionState = checking
current peerConnection.iceConnectionState = checking
current peerConnection.iceConnectionState = checking 
current peerConnection.iceConnectionState = checking 
**current peerConnection.iceConnectionState = checking
ICE failed, see about:webrtc for more details
current peerConnection.iceConnectionState = failed**

**Comment by lherman-cs** [comment]
From your logs, it looks like your master has sent and received ice candidates, formed candidate pairs, but failed in the connectivity check. 

I think there are some possibilities that happened here:
1. All of your candidate pairs are simply not compatible. So, it kept sending connectivity checks and finally hit a timeout.
2. Master/Viewer got disconnected from the network during the connectivity check, which would cause the master keep asking if the connection is healthy but never got any response, and finally hit a timeout.

To help diagnosing the problem more accurately, would you mind to share some more details?
1. Information about gathered local and remote candidates, e.g. IP address, candidate type (host, reflexive, or relay), local/remote.
   * If you're using chrome, you can get the information from `chrome://webrtc-internals/`
   * If you're using firefox, you can get the information from `about:webrtc`
   * In general, you can also capture it from [onicecandidate callback](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onicecandidate) and from the signaling server:
      * [From onicecandidate](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/master.js#L140)
      * [From signaling server](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/master.js#L192)
2. Were both master and viewer running using the JS sdk?
3. What browsers/environments the master and the viewer were in?
4. What was the `NAT Traversal` setting?

**Comment by lherman-cs** [comment]
Due to inactivity, I'll close this. Please feel free to reopen it if you need further assistance.
