### ISSUE TITLE
[QUESTION] Can I work with videos on a frame-by-frame basis?

### ISSUE THREAD

**Issue by schr0din9ersCat** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#42]
Can I work with videos on a frame-by-frame basis?
 For example, you want to edit a video in Paint and send it to the other person in real time.

**Comment by lherman-cs** [comment]
@schr0din9ersCat our SDK only provides the signaling side. So, I think you can work with video on a frame-by-frame basis using the browser APIs. AFAIK, [canvas](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API) is your best bet for manipulating the video frames in real time as it uses WebGL and very flexible. 

I would say the steps are:
1. Get the video source from [getUserMedia](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia)
2. Attach the video stream to a canvas and manipulate the frames through Canvas APIs ([please read here for more details](https://developers.google.com/web/updates/2016/10/capture-stream))
3. Send the canvas' track to the other peer

**Comment by schr0din9ersCat** [comment]
Thank you very much. I'll try.

**Comment by lherman-cs** [comment]
Due to inactivity, I'll close this. Please feel free to reopen it if you need further assistance.
