### ISSUE TITLE
If sendVideo = false on firefox, it generate a error as "Viewer"

### ISSUE THREAD

**Issue by BurguerJohn** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#46]
How to reproduce:
Set:
`sendVideo = false`
on `getFormValues()`

Comment this inside of the function:
`viewer.signalingClient.on('open', async () =>`

`
try {
            viewer.localStream = await navigator.mediaDevices.getUserMedia(constraints);
            viewer.localStream.getTracks().forEach(track => viewer.peerConnection.addTrack(track, viewer.localStream));
            localView.srcObject = viewer.localStream;
        } catch (e) {
            console.error('[VIEWER] Could not find webcam: ' + e);
            return;
        }
`
or else it will demand you have a webcam.

It should work fine for chrome. You can see the master, but the master can't see you.

For firefox. it throw:
> ICE failed, your TURN server appears to be broken, see about:webrtc for more details

And the connection fails.

**Comment by BurguerJohn** [comment]
Just by calling this function:
` await navigator.mediaDevices.getUserMedia(constraints);`
It make it work.
If we refuse the permission to the camera, it give a internal error. It might be a firefox bug.

**Comment by BurguerJohn** [comment]
It seen related to this:
[https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/148](url)

**Comment by lherman-cs** [comment]
> Just by calling this function:
> ` await navigator.mediaDevices.getUserMedia(constraints);`
> It make it work.
> If we refuse the permission to the camera, it give a internal error. It might be a firefox bug.

It's expected that it threw an error. According to https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia, if the user refused to give permission, it'll reject the promise with `NotAllowedError`

**Comment by BurguerJohn** [comment]
This is not the issue.
The problem ccur at some internal call from firefox that generate two empty transmitters if offer is set to sendrecv (that it seen impossible to change for now) and there is no permission to access the user media.

**Comment by lherman-cs** [comment]
@BurguerJohn are you using the C SDK for the viewer? AFAIK, the issue that you're referring to only exists in our webrtc C SDK. The issue is that when we receive the offer from the browser, we ignore their tranceivers' directions and we simply reply with `sendrecv` always.

**Comment by BurguerJohn** [comment]
@lherman-cs Not at all, I am using the js version.
Here, I made a fork to help.
https://github.com/BurguerJohn/amazon-kinesis-video-streams-webrtc-sdk-js
As you can see, my only commit was removing the mandatory webcam in the client side and adding the missing js file.

So I start a Master with:
Video / Audio / DataChannel

And I only need Datachannel from the client. So i disable the Video / Audio Channel.
Starting the Viewer in Chrome work fine. But on firefox it throw the message:
`ICE failed, your TURN server appears to be broken, see about:webrtc for more details`

And looking inside the about:webrtc:
```
(registry/INFO) insert 'ice' (registry) succeeded: ice

(registry/INFO) insert 'ice.pref' (registry) succeeded: ice.pref

(registry/INFO) insert 'ice.pref.type' (registry) succeeded: ice.pref.type

(registry/INFO) insert 'ice.pref.type.srv_rflx' (UCHAR) succeeded: 0x64

(registry/INFO) insert 'ice.pref.type.peer_rflx' (UCHAR) succeeded: 0x6e

(registry/INFO) insert 'ice.pref.type.host' (UCHAR) succeeded: 0x7e

(registry/INFO) insert 'ice.pref.type.relayed' (UCHAR) succeeded: 0x05

(registry/INFO) insert 'ice.pref.type.srv_rflx_tcp' (UCHAR) succeeded: 0x63

(registry/INFO) insert 'ice.pref.type.peer_rflx_tcp' (UCHAR) succeeded: 0x6d

(registry/INFO) insert 'ice.pref.type.host_tcp' (UCHAR) succeeded: 0x7d

(registry/INFO) insert 'ice.pref.type.relayed_tcp' (UCHAR) succeeded: 0x00

(registry/INFO) insert 'stun' (registry) succeeded: stun

(registry/INFO) insert 'stun.client' (registry) succeeded: stun.client

(registry/INFO) insert 'stun.client.maximum_transmits' (UINT4) succeeded: 7

(registry/INFO) insert 'ice.trickle_grace_period' (UINT4) succeeded: 5000

(registry/INFO) insert 'ice.tcp' (registry) succeeded: ice.tcp

(registry/INFO) insert 'ice.tcp.so_sock_count' (INT4) succeeded: 0

(registry/INFO) insert 'ice.tcp.listen_backlog' (INT4) succeeded: 10

(registry/INFO) insert 'ice.tcp.disable' (char) succeeded: \000

(generic/ERR) UDP socket error:Internal error at /builds/worker/checkouts/gecko/dom/network/UDPSocketParent.cpp:268 this=0000019A8F414800

(ice/ERR) ICE(PC:1589559436527000 (id=2147483651 url=http://localhost/webrtcFork/amazon-kinesis-video-streams-webrtc-sdk-js/examples/)): failed to find default addresses

(generic/ERR) UDP socket error:Internal error at /builds/worker/checkouts/gecko/dom/network/UDPSocketParent.cpp:268 this=0000019A8E65CC00

(ice/ERR) ICE(PC:1589559436527000 (id=2147483651 url=http://localhost/webrtcFork/amazon-kinesis-video-streams-webrtc-sdk-js/examples/)): failed to find default addresses
```

**Comment by lherman-cs** [comment]
Which Firefox version did you use? I tried your fork and I didn't find any issue with it. Following is my setup:

Chrome: 81.0.4044.138
Firefox: 74.0.1

Following is the demo:
![demo](https://user-images.githubusercontent.com/15654932/82077037-b432f080-96ac-11ea-9fce-70001055ad37.gif)

**Comment by BurguerJohn** [comment]
@lherman-cs First of all I want to thank you for all the fast answers and i really appreciate you spending time trying to fix mt problem, thanks!

I am using the lasted public version `76.0.1 (64-bits)` and just gave it a try with the "Turn only" option since i was using the "Stun/turn" option, but the error still remains.

I will try to create a gif showing it here. This error occur both in my localhost and our ElasticBeans server.

**Comment by BurguerJohn** [comment]
I just discovered something while recording. By using "Turn Only" it sometimes work correctly with firefox. My first try connected successful. After that it started to give the old error again. Not sure if STUN/TURN can work sometimes as well, but it never happened with my tests.

1) Started the master on Chrome
2) Trying viewer in firefox. Give error.
3) Trying viewer in Chrome, forgot to disable video/audio channel, but it work even with those disabled:
https://streamable.com/e6nrq0

**Comment by lherman-cs** [comment]
So, I found a small issue when it's data channel only mode, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/48. The browser seems to be not happy when you provide the constraints to `getUserMedia` with video and audio set to false. Since, it'll throw an error, the flow becomes invalid. 

I'm not sure, if this will fix your problem, but maybe you can try to the fix, https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/pull/48?

**Comment by lherman-cs** [comment]
About stun/turn thing, do you know if you could connect by using ice candidates from STUN only?

**Comment by lherman-cs** [comment]
Due to inactivity, I'll close this. Please feel free to reopen it if you need further assistance.

**Comment by rajnada** [comment]
@lherman-cs
I am facing the same issue could you suggest me where I am getting wrong
Thanks in advance :)
