### ISSUE TITLE
Is it possible to start a chat if the viewer connects to the channel before the master?

### ISSUE THREAD

**Issue by rabbitfufu** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#47]
I am setting up a one-on-one master-viewer webrtc chat based on the code in the examples directory.  

The example code works great -- but only if the master is connected to the channel before the viewer.  (Viewer sends an SDP offer immediately after connection, which is received by the master.)

As it is, if the viewer refreshes their page, the chat will automatically resume.  However, if the master refreshes their page, the chat dies.

I am wondering:  Is this a limitation of kvs?  Or is it possible for the master to also send an SDP offer when it connects, in case there is already a viewer connected to the channel?

**Comment by marcusbelcher** [comment]
I concur. I have an app using Kinesis in production. A significant amount of logic handling race conditions is needed for 2 unknown people (who is a master or viewer does not matter) to have an on demand none scheduled video call and for it to "just work". 

Having the this would allow me delete a significant amount of code.

**Comment by bdhandap** [comment]
Viewer can connect before the master and when the master connects it should receive any pending SDP message (offer/answer/candidate) if it is within TTL. However, I have seen few times where this doesn't work intermittently and we do have a fix in place which is pending deployment.   

>  is it possible for the master to also send an SDP offer when it connects

Initially signaling service allowed only viewers to send offer but we recently deployed a feature which will allow master to send SDP offers as well (which should address re-negotiation, ice restarts, etc)

**Comment by rabbitfufu** [comment]
This is good to know, appreciate the information.  I will experiment with sending SDP offers as the master and watch for that update you mention.   (My own experience is that the master never receives the SDP message if it connects after the viewer, but hopefully the update will affect this.)

**Comment by MushMal** [comment]
Resolving the issue for now. Please re-open or cut a new one and we will be happy to help
