### ISSUE TITLE
Can't import the named export 'Crypto' from non EcmaScript module

### ISSUE THREAD

**Issue by tomeraz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#55]
Using SigV4RequestSigner on node.js with webpack and getting the following error on build:
```
ERROR in .../node_modules/isomorphic-webcrypto/src/index.mjs 2:19-25
Can't import the named export 'Crypto' from non EcmaScript module (only default export is available)
 @ .../node_modules/amazon-kinesis-video-streams-webrtc/lib/SigV4RequestSigner.js
 @ .../node_modules/amazon-kinesis-video-streams-webrtc/lib/index.js
 @ .../createStreamingChannel.js
```

How can fix this?

**Comment by lherman-cs** [comment]
@tomeraz it looks there's something wrong with your webpack configuration. In Javascript world, some libraries don't support all module systems. So, it's common to configure your webpack to parse these libraries differently. To do that, I would suggest to check your parser config, https://webpack.js.org/configuration/module/#ruleparser.

**Comment by tomeraz** [comment]
@lherman-cs thanks. Any idea which webpack rule should configured for this lib to build properly?

**Comment by tomeraz** [comment]
Was able to put 'amazon-kinesis-video-streams-webrtc' inside a lambda layer and use it as external dependency with my node.js serverless webpack bundle
