### ISSUE TITLE
Removing the need for client side master

### ISSUE THREAD

**Issue by marcusbelcher** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#57]
Hi all,

I would like to know if the following is possible and/or if there is a mechanism to achieve this. 

In an effort to simplify client side logic and remove the need for client side master. I would like all client side users to be "viewers". I would like master to be dummy user server side (no video, just passing messages to viewers). My problem is my server is load balanced via fargate. Is there a mechanism for the signalling server to use Redis to share connection information. E.g. A similar approach is typical with socket.io https://medium.com/containers-on-aws/scaling-a-realtime-chat-app-on-aws-using-socket-io-redis-and-aws-fargate-4ed63fb1b681

For me this is closer to a typical signalling server. 

Best,

**Comment by lherman-cs** [comment]
Hey, we actually have an update to make this happen! Please watch for an update from us.

**Comment by onhate** [comment]
👀

**Comment by MushMal** [comment]
Resolving for now. Will update as soon as we have more info
