### ISSUE TITLE
Get a signal/message/notification for "Viewer" when "Master" starts/stops connection to signaling channel

### ISSUE THREAD

**Issue by mjnaik** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#58]
For peer-2-peer WebRTC based communication using KVS Signaling Channel, I am looking for a way in WebRTC for JavaScript SDK to get a “signal” / “message” / “notification” or whatever, so that Viewer code knows that Master has connected to the channel. The use case is very simple, that when a master wants to initiate a peer-2-peer communication, the receiver needs to know somehow that someone started a call and would like to communicate. E.g. Master makes a call, it rings on Viewer’s side (notification that I am looking for), and viewer accepts (negotiates P2P connection) and start communication. 

For the example, it is little hard to understand how that scenario would work, because it is assumed in the example to click on "Start Master" and then "Start Viewer".

We are working on a solution where we are stuck with "Viewer" not able to know when "Master" starts or stops connection to a Signaling Channel. 

How can the "Viewer" receive a notification when "Master" starts or stops connection with Signaling Channel? 

"Master" uses "WebRTC SDK in C for Embedded Devices"
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-c.html 

"Viewer" uses "WebRTC SDK in JavaScript for Web Applications"
https://docs.aws.amazon.com/kinesisvideostreams-webrtc-dg/latest/devguide/kvswebrtc-sdk-js.html 

Here, both "Master" and "Viewer" are connecting to same Signaling Channel.

**Comment by lherman-cs** [comment]
Here are some thoughts on this which you might be able to use for your application:

* The signaling service will keep the message and attempt to deliver within the TTL of the message that's defined when the signaling channel was created. So, the viewer could send a message and the master would pick it up even if it connects after the viewer.

* The application could create a data channel for triggering your application events. The viewer then could subscribe to the master through this data channel, and the master can emit a "start" or "stop" event.

* The application could also choose to use other means of communications - for example, some of the embedded devices use IoT with MQTT.

**Comment by MushMal** [comment]
To also add.. Some customers could choose to swap the master and viewer applications - the JS could act as a master that awaits and the embedded could become the viewer (really bad naming). In this case, whenever the embedded device (the viewer) starts up, it will try to connect to the master and exchange would happen.

**Comment by mjnaik** [comment]
> To also add.. Some customers could choose to swap the master and viewer applications - the JS could act as a master that awaits and the embedded could become the viewer (really bad naming). In this case, whenever the embedded device (the viewer) starts up, it will try to connect to the master and exchange would happen.

It is an interesting take. Considering the JS browser is acting as "master", and the embedded is acting as "viewer", there could not be more than one JS browser watching what the embedded is sending media, is that correct?  The reason I am asking is because we would need upto 10 JS browser "viewers"  who can watch video from the embedded system.

**Comment by MushMal** [comment]
@mjnaik I see, this "swapping" will only work for 1:1 in this case - you won't be able to have multiple "masters".

You can increase the TTL of the message but ideally, if the delay is arbitrary, you might consider some notification - similar to IoT MQTT

**Comment by lherman-cs** [comment]
Due to staleness. I'll close this issue. Please feel free to reopen if you need further assistance.
