### ISSUE TITLE
websocket forbidden 403

### ISSUE THREAD

**Issue by tomeraz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#59]
I'm using ```SigV4RequestSigner``` to presign a WebSocket url in aws lambda.
In the client when attemtping to call ``` new SignalingClient()``` with a requestSigner that returns the presigned url from the server I'm getting the following error:
```
Error during WebSocket handshake: Unexpected response code: 403
```
What could be the reason?
Could this be a CORS issue?

**Comment by tomeraz** [comment]
Solved when adding the ```kinesisvideo:ConnectAsMaster``` permission to the lambda function which signs the url.

**Comment by SuiKaSan** [comment]
@tomeraz I had the same issue. I'm trying to create a signaling client using `new SignalingClient` but failed with 403.
![微信截图_20201201113436](https://user-images.githubusercontent.com/44567811/100694216-94091b80-33c9-11eb-956a-2f1eb439a359.png)
 Can you tell me how you solved the question specifically ?
