### ISSUE TITLE
Get kinesis video stream webrtc playback

### ISSUE THREAD

**Issue by tomeraz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#60]
Is there a way to get the webrtc signaling channel recording from s3?

Can i use [GetClip sdk](https://docs.aws.amazon.com/kinesisvideostreams/latest/dg/API_reader_GetClip.html) to get it?

Is there a way to store the signaling channel data to a kinesis video stream?

**Comment by MushMal** [comment]
@tomeraz I am not sure I understand your question. Perhaps, what you mean is the WebRTC streaming recorded to S3? The signaling channel is used only to exchange answers and offers between peers.

If your question is about the former, there is no way currently to do it.

One of the solutions for embedded is to use dual streaming mode (KVS + WebRTC) in which case your peer will use WebRTC and will also need to stream KVS for the persistence and in which case you could access the stream via any of the GetMedia APIs.

We had an old sample here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/tree/kvs_persistence

**Comment by tomeraz** [comment]
Thanks for your reply.

I want to record webcam video from the browser but I don't know when recording is done, so I need to stream it to s3 somehow.

Thought webrtc to kvs is using s3 as the underlaying layer.

Is there a way to stream webrtc using javascript to s3 or kvs video channel that can be stored in s3?

**Comment by MushMal** [comment]
Not currently. However, I am still not sure about your scenario. If you just need to upload pre-recorded video to S3 then you can use the AWS SDK for JS and upload the file,.

**Comment by tomeraz** [comment]
@MushMal it's not pre-recorded. It's recorded during webapp usage.

Right now I record video and upload it at the end of usage. But some people close the browser before upload is complete or upload fails due to the size of the file and internet connection speed. So we want to stream the video and record it on the server, on a serverless architecture.

Thought KVS would be a solution because docs say it uses s3 and has a getclip method. I didn't realize it relates to video channel api, which doesn't have browser js api. Signaling channel api has js api but cannot store video. It confused me as I am new to KVS.

**Comment by doublepithre** [comment]
@MushMal  adding to @tomeraz 's input, we can't rely on uploading the recording after the stream is ended in case of longer video sessions(let's say 1hr or even 30mins) as the video file size will be very huge. If there is a way to save the media directly to S3 while it is streaming there won't be any such issues.

Can you let us know whether there is a way to do this?

1) User starts the session in Master mode and starts recording the screen
2) The media is saved in S3 while it is being streamed

**Comment by MushMal** [comment]
Unfortunately, there is no straight-forward way of achieving this. There is a C-SDK based sample that does dual-streaming from master where it serves the WebRTC as well as uploads the stream to KVS but for Browser scenario (JS) you will need to access the user media directly and somehow upload it. I don't have the details though.

**Comment by tomeraz** [comment]
The serverless way I found for our solution is so use Twilio for streaming, fetch recordings composition and transfer them to s3

**Comment by doublepithre** [comment]
@tomeraz If you can elaborate on the above it will be very helpful.

**Comment by tomeraz** [comment]
Twilio is external to aws.
You can open a room, send video streaming there.
They have an api to create a playable video composition of the room recorded tracks.
You specify a callback, in our case an api gateway to a lambda function.
Once we receive composition-available status in the callback, we get a url, download it to the lambda and upload it to s3

**Comment by itsmurali** [comment]
I'm also here hoping KVS WebRTC can support Playback live and recorded video streams. Looks like that's not possible. 

I see an option called `TURN Only (force cloud relay)`, is there a way to store stream to S3 without a producer? The problem here is like others we are fully depending on browser based solution and having a dual stream is going to be an expensive for the end users who have to stream twice. Looks like conceptually JS/browser based producer is also not available for Video Stream.

If we need to record/archive, we have to have a backend server that act as a Viewer and Producer, which pushes to Video Stream, is that correct? Thanks.

**Comment by MushMal** [comment]
Unfortunately TURN server can’t have access to the stream bits - it truly is a relay server with no way of decrypting the bits.

The suggestion of having a cloud based peer (SFU like) that can act as a producer of a stream and a relay is a good one but will require some architecting as KVS doesn’t support it out of the box.

Do you mind resolving the issue as the original question was answered? Please feel free to cut new issues if you need more help
