### ISSUE TITLE
Could not find webcam issue

### ISSUE THREAD

**Issue by suvojitkar** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#64]
Hi All.

I am pretty new webrtc and ec2 deployment. I was trying this sample app and it worked perfectly fine when i am running in local (macos). I deployed this in ec2 instance and i am getting error that **Could not find webcam**

Logs:
[2020-06-13T12:20:38.429Z] [INFO] Page loaded
[2020-06-13T12:20:46.754Z] [INFO] [MASTER] Channel ARN:  arn:aws:kinesisvideo:us-west-2:884132714130:channel/suvojitrajkar/1592031129082
[2020-06-13T12:20:47.774Z] [INFO] [MASTER] Endpoints:  {
  "WSS": "wss://m-8a150cee.kinesisvideo.us-west-2.amazonaws.com",
  "HTTPS": "https://r-34a7a751.kinesisvideo.us-west-2.amazonaws.com"
}
[2020-06-13T12:20:50.232Z] [INFO] [MASTER] ICE servers:  [
  {
    "urls": "stun:stun.kinesisvideo.us-west-2.amazonaws.com:443"
  },
  {
    "urls": [
      "turn:54-190-105-65.t-4f692171.kinesisvideo.us-west-2.amazonaws.com:443"
    ],
    "username": "1592051150:djE6YXJuOmF3czpraW5lc2lzdmlkZW86dXMtd2VzdC0yOjg4NDEzMjcxNDEzMDpjaGFubmVsL3N1dm9qaXRyYWprYXIvMTU5MjAzMTEyOTA4Mg==",
    "credential": "1U+vG0GH8VoArC9myxbc7YD2+RYRgpq6tUHxuloOPQ0="
  }
]
[2020-06-13T12:20:50.233Z] [ERROR] **[MASTER] Could not find webcam**
[2020-06-13T12:20:50.233Z] [INFO] [MASTER] Starting master connection
[2020-06-13T12:20:50.236Z] [ERROR] [MASTER] **Signaling client error**

I also came across :

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-c/issues/449

https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/36

But didn't find an exact answer.

I tried loading the webpage in chrome (Version 81.0.4044.138) and even in firefox(77.0.1).Although the form page loads well, its unable to start video capture for a master or viewer. Issue is observed in both the browser.

**Comment by MushMal** [comment]
As the error states, it can’t find the webcam. The linked issue had exact same question. The app needs to have access to the camera to start.

**Comment by suvojitkar** [comment]
@MushMal Well, my question specifically is : It works in localhost. Its the same code as present in repo. Nothing different. But it shows this error as i host it on a S3 bucket. Not sure why its not able to detect my webcam from S3. Can you share your thoughts?

Alpreciate your help!

**Comment by lherman-cs** [comment]
@suvojitkar the issue is not related to the SDK, we only use an API provided by the browser to get frames from the camera,  `getUserMedia`.

Regarding your app works fine on localhost but not when you access it from S3, it's very likely because you access your website without https. Browsers only allow secure access to the camera, except on localhost (for development purpose only).

**Comment by suvojitkar** [comment]
Thanks @lherman-cs . Its works in https. :)

**Comment by rfndzc** [comment]
Confronting the same message.  I'm running the master without issue on a Raspberry PI with the C SDK streaming the demo ball animation and audio.  I can view the animation fine when accessing the stream via the JS SDK test page running on my laptop's localhost.  When I try to access the stream via the Kinesis test page, I get the 'Could not find webcam' error.  

I thought perhaps it would be related to the demo animation being streamed by the master as a sort of mock webcam and this is somehow blocked on https, but I do not currently have a webcam on the RPI to verify any alternative, nor am I really familiar at all with the C SDK makeup to see how the demo stream is being implemented.  For now it does not work for me.  I will try again with an actual cam feed for the RPI to see if this error persists.
