### ISSUE TITLE
Peer communication

### ISSUE THREAD

**Issue by bangersandflash** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#66]
I believe KVS currently supports MASTER and VIEWER roles whereby a MASTER can communicate with all VIEWERS however a VIEWER can only communicate with a MASTER and not with other VIEWERS.

I'm looking for a way that supports all peers communicating with each other e.g a stream with 3+ users communicating via webcams. Is this currently a possibility with KVS?

**Comment by tejas1234567** [comment]
Same doubt

**Comment by MushMal** [comment]
Full mesh is not currently supported. This is one of the features that people ask for and we will prioritize it accordingly.

I am resolving this issue. Will update as soon as we roll something out

**Comment by juku1999** [comment]
Is full mesh currently supported?
