### ISSUE TITLE
How to create a session token for AWS.KinesisVideo?

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#72]
I would like to know how do I create a session token to be used in the AWS.KinesisVideo options?

**Comment by chehefen** [comment]
it's a temporary AWS credential. You can get it using aws cli: https://docs.aws.amazon.com/cli/latest/reference/sts/get-session-token.html

**Comment by lherman-cs** [comment]
Since the question has been answered, I'll mark this as resolved. Please feel free to reopen it for further assistance!
