### ISSUE TITLE
SignalingClient.ts:140 WebSocket connection to 'wss://.....' failed:  Error during WebSocket handshake: Unexpected response code: 403

### ISSUE THREAD

**Issue by rRaijin** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#73]
Hello. This is my first experience connecting this AWS service. I have standart React App with using aws amplify

I added the code from your example to my application. Everything works when I connect to the Master, but when in another window I try to authenticate with another authenticated user to join the channel, the Viewer gives me this error:

![Screenshot from 2020-07-15 12-31-25](https://user-images.githubusercontent.com/29259035/87529096-27e67f00-c697-11ea-8dd8-8ada43bc1e56.png)

Please tell me why this is happening. What am I doing wrong, and can I check this on localhost?

P.S. I did not configure Load Balancer and did not create SSL / TLS Certificate.

Thanks for help

**Comment by chadlittle** [comment]
How did you resolve this @rRaijin
