### ISSUE TITLE
STUN host lookup received error

### ISSUE THREAD

**Issue by fernandoc1** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#74]
I'm receiving an "STUN host lookup received error" when trying to connect to my stream.
How can I fix this?
![image](https://user-images.githubusercontent.com/249402/87825788-24e1bf00-c84e-11ea-8149-6cbcaefffbea.png)

**Comment by disa6302** [comment]
@fernandoc1 , 
It looks like your host candidate is IPv6 and we do not support IPv6.

**Comment by lherman-cs** [comment]
@fernandoc1 any update?

**Comment by lherman-cs** [comment]
Since the issue has gone stalled, I'll mark this as resolved. Please feel free to reopen it for further assistance!
