### ISSUE TITLE
[QUESTION] Support to run on iOS devices

### ISSUE THREAD

**Issue by RidClick** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#80]
I have installed this package for an app in ionic cordova and in Android it works perfectly on a device, but in iOS since the webRTC is not available it forces me to install other plugins like cordova-iosrtc with which I can access the navigator.getUserMedia().

But the problem is that this plugin is the one that makes the connection with AWS KVS and when trying to send the MediaStreamTrack through the SignalingClient I get an error of RTCPeerConnection.addTrack must be an instence of MediaSrteamTrack.

It may not be the proper way to proceed but I need a helping hand.

**Comment by lherman-cs** [comment]
@RidClick I'm not sure why you need to send MediaStreamTrack through the signaling client. Signaling client should be used for exchanging offer/answer and ice candidates. MediaStreamTrack should be received through `getUserMedia` or from the webrtc callback (which will get called after exchanging offer/answer).

**Comment by MushMal** [comment]
Resolving as non-kvs specific
