### ISSUE TITLE
question: is camera mandatory in both sides?

### ISSUE THREAD

**Issue by cesarpachon** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#81]
hi.. in a situation with a master and a single client, if the client doesn't have a camera, it is yet possible to establish communication? (I make use of data channel to send commands) so the client can see master camera, but the master receives only the data channel messages? 
or webrtc demands that both sides have video and audio channels? thanks for answer this newbie question..

**Comment by lherman-cs** [comment]
Hey no worries, you can send an arbitrary amount of them, even none at all. This can happen by exchanging offers and answers at the beginning of the session, both parties then need to agree with the offer/answer (contains the metadata necessary about the amount of data/video/audio channels, their codecs, reliability, etc.) to make a session.

**Comment by cesarpachon** [comment]
thank you for the quick answer!
