### ISSUE TITLE
KVS WebRTC test page does not display received data channel messages

### ISSUE THREAD

**Issue by bryan-hicks** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#85]
Both viewer.js and master.js assign a function for handling data channel messages to the `RTCPeerConnection.ondatachannel` property like so:
[viewer.js](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/viewer.js#L100):
```
if (formValues.openDataChannel) {
    viewer.dataChannel = viewer.peerConnection.createDataChannel('kvsDataChannel');
    viewer.peerConnection.ondatachannel = event => {
        event.channel.onmessage = onRemoteDataMessage;
    };
}
```
[master.js](https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/master.js#L129):
```
if (formValues.openDataChannel) {
    master.dataChannelByClientId[remoteClientId] = peerConnection.createDataChannel('kvsDataChannel');
    peerConnection.ondatachannel = event => {
        event.channel.onmessage = onRemoteDataMessage;
    };
}
```

However, this event handler is only called when the remote peer calls `createDataChannel` (documentation [here](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ondatachannel)). Since the test page is the one calling `createDataChannel`, the event handler will never be called.

Instead, the function for handling data channel messages should be assigned to the `RTCDataChannel.onmessage` property like so:
viewer.js:
```
if (formValues.openDataChannel) {
    viewer.dataChannel = viewer.peerConnection.createDataChannel('kvsDataChannel');
    if (viewer.dataChannel) {
        viewer.dataChannel.onmessage = onRemoteDataMessage;
    }
}
```
master.js:
```
if (formValues.openDataChannel) {
    master.dataChannelByClientId[remoteClientId] = peerConnection.createDataChannel('kvsDataChannel');
    if (master.dataChannelByClientId[remoteClientId]) {
        master.dataChannelByClientId[remoteClientId].onmessage = onRemoteDataMessage;
    }
}
```

**Comment by chehefen** [comment]
Data channel requires both side to createDataChannel in order to work. The event handler should be triggered by each party's createDataChannel. Can you clarify what scenario is not working for you?

**Comment by MushMal** [comment]
Resolving as stale
