### ISSUE TITLE
Issue using python flask

### ISSUE THREAD

**Issue by wolfviking0** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#87]
Hello, I am using the webrtc sdk with electron and it's working fine, I decide to add the webrtc support to my flask application.

I try to reuse the exact same code but unfortunately I received this error :

[VIEWER] Signaling client error:  TypeError: Cannot read property 'digest' of undefined
    at Function.<anonymous> (SigV4RequestSigner.ts:175)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)
    at tslib.es6.js:73
    at new Promise (<anonymous>)
    at Module.__awaiter (tslib.es6.js:69)
    at Function.window.KVSWebRTC../src/SigV4RequestSigner.ts.SigV4RequestSigner.sha256 (SigV4RequestSigner.ts:174)
    at SigV4RequestSigner.<anonymous> (SigV4RequestSigner.ts:103)
    at step (tslib.es6.js:99)
    at Object.next (tslib.es6.js:80)

I am trying different approach, but so far I was not successful. Any suggestion about how I can fix this this trouble ?
Thanks

**Comment by lherman-cs** [comment]
@wolfviking0 there's really no differences between using the SDK with electron vs flask, both will be running inside of the browser environment. 

How did you bundle your Javascript source? Did you setup your flask to properly load your assets at the right endpoints?

**Comment by wolfviking0** [comment]
@lherman-cs thanks for your response.

So I am using the javascript from source and I build it using nom run build-all
I am not using the min js, the full one.

For the setup of flask, it could be the issue, what do you mean by setting the right endpoints ?

Thanks

**Comment by wolfviking0** [comment]
To complete my previous message the JS code is really close to the sample you have here : https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/examples/viewer.js

Do you think I need to do some change similar to this example : https://github.com/iidd0101/flask-kinesis/blob/master/flask_kinesis.py, for the kinesis crendential ?

**Comment by lherman-cs** [comment]
@wolfviking0 ah I see. Yes, WebRTC requires secure connection, WebRTC APIs will only be available on localhost and HTTPS.

**Comment by wolfviking0** [comment]
So I was able to launch using a certificate over https.
Thanks.
