### ISSUE TITLE
How to hide credentials?

### ISSUE THREAD

**Issue by rohitcoder** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#88]
Hi there, 

I am trying to minimize risk as much as possible, i was thinking to implement it with AWS STS service, where every user will get temporary access ID, access secret and session token to use with Kinesis service.

But, still these tokens will be visible and can be use in wrong way, isn't there any way to just hide these tokens or use only session Token, or signatures something like that?

### RequestSigner

 i'd a look over that part in Docs, but still its not clear to me, can you send me link of appropriate complete docs which demonstrates how to implement `new AWS.KinesisVideo({})` with `requestSigner`

I am already having experience with generating preSignedUrls in S3 and API gateway, i believe here we have to do something, i just little bit confused how to integrate that signing part with this KinesisVideo function.

**Comment by MixMasterMitch** [comment]
The KVS WebRTC SDK and the AWS SDK are different assets and have different credentials options. The `RequestSigner` is usable with the KVS WebRTC SDK, not the AWS SDK.

If your goal is to not have any AWS credentials present on the client, then all of the operations using the AWS SDK (creating/describing channels and getting ICE config) need to be handled on some sort of proxy service that makes calls to AWS APIs and returns back the needed info (e.g. ICE Config, Channel ARN, Channel endpoint) to the client. Then a custom `RequestSigner` needs to be provided to the KVS WebRTC SDK that makes calls to your service to get a pre-signed URL for the KVS signaling service.

**Comment by itsmurali** [comment]
Hi @MixMasterMitch -- thanks for your response as I'm also in a similar situation like @rohitcoder. So if I understand correctly, we should be using KVS WebRTC SDK to create credentials in the backend, correct? If so, do you have any backend code samples (specifically for .NET or C#) on how to do it?

**Comment by MixMasterMitch** [comment]
> we should be using KVS WebRTC SDK to create credentials in the backend

I don't think that is correct. More accurate would be: Generate a pre-signed URL on the backend using AWS credentials and then use that pre-signed URL with the KVS WebRTC SDK on the client side. 

> do you have any backend code samples (specifically for .NET or C#) on how to do it?

No, just the JS code here: https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/blob/master/src/SigV4RequestSigner.ts

**Comment by vniranjankumar** [comment]
HI @MixMasterMitch - Trying to understand how to "use that pre-signed URL with the KVS WebRTC SDK on the client side."

Should we write our own class "MyCustomRequestSigner" implements RequestSigner ? and pass the MyCustomRequestSigner in the constructor of SignalingClient ?

**Comment by vniranjankumar** [comment]
Ok, I think i solved it, I am able to Implement RequestSigner and override the getSignedURL method.

**Comment by MixMasterMitch** [comment]
Great! Implementing a class that extends RequestSigner is what I meant.

**Comment by MushMal** [comment]
Resolving. Please feel free to cut a new issue

**Comment by bgunner** [comment]
> Ok, I think i solved it, I am able to Implement RequestSigner and override the getSignedURL method.

Hi vniranjankumar, I hope you're doing well.

I'm trying to do something similar. 
I have a java backend but the **AWS.KinesisVideo({})** code resides on js, in the client. So I want to avoid showing the AccessKey and Secret on the js. Can you please give me a hand on how did you achieve this? 

For s3, for example, I do the following: On the BE I generate a signed url and return it to FE so the user can post files to s3 or read them. I thought I'd be able to sign an URL for KVS, just like I do for s3, and send it to FE so the user would be able to post to the stream (or connect as a viewer only).
I really appreciate any help. Thanks in advance.

**Comment by himalreddy** [comment]
https://blog.learningdollars.com/2021/05/09/aws-kinesis-video-stream-with-signed-url/

This Document helped a lot. Just for reference.

In this doc also they are using access key and secret key how to replace with IAM roles.
