### ISSUE TITLE
SFU with Kinesis video stream SDK js

### ISSUE THREAD

**Issue by Nokama4** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#89]
I built a React.js and Node.js app, inspired by KVS example .

It is working for a few participants, a Master can stream his webcam video & audio via WebRTC, and get every viewer webcam video. But we realized it won't be suitable for 50 people as the Master CPU and network increase over each viewer connection. For every viewer a peerConnection is created with Master. We'd rather the Master to send his stream only once to a server which will forward it to all the viewers

We would like to go for a SFU solution, would it be possible with the Javascript SDK ? It is advised for the C SDK to use putMedia & GStreamer, is there an equivalent in javascript ?

**Comment by MushMal** [comment]
SFU or MTU is not currently supported. We will update as soon as we have more info
