### ISSUE TITLE
audio and video control of participants.

### ISSUE THREAD

**Issue by jomisoac** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#90]
Hello, how are you? I am trying to create a video conference application for holding assemblies, in which a maximum of hundreds of people could connect to the call.
I have a question, and it is that I need to be able to have control of the audio and video of each participant in the call, as well as to have control of my video and audio, a zoom style or meet. is it possible to do it with the javascript sdk.?

**Comment by lherman-cs** [comment]
@jomisoac I'd highly recommend to use a data channel. By using a data channel, you can develop your application protocol. Since it's a full duplex connection, each peer can communicate back and forth however you wish.

**Comment by MushMal** [comment]
Resolving
