### ISSUE TITLE
Doing something locally when remote video stream is paused

### ISSUE THREAD

**Issue by fatukunda** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#91]
Is there a way to know when a remote video stream is paused? I would like to know when the remote user pauses their video so that I can show a different screen instead of the black screen that appears. Any ideas on how I can achieve this?

**Comment by hassanctech** [comment]
I just want to make sure I understood your question correctly.  For example there is peer A and peer B.  Peer B is sending video to peer A.  Peer B decides to pause its stream (so it stops sending video to peer A).  You would like peer A to be able to detect that peer B paused the stream so peer A can display a different screen, is that correct?

**Comment by fatukunda** [comment]
Yes that's correct @hassanctech

**Comment by lherman-cs** [comment]
@fatukunda you can definitely achieve this by listening to `mute` (paused) and `unmute` (unpaused) events, https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/mute_event for the track that you're interested in.

To get the remote tracks, you need to listen to the `track` event from peer connection, https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack. From that event, you can extract the [MediaStream](https://developer.mozilla.org/en-US/docs/Web/API/MediaStream), which later you can use `getTracks`, `getVideoTracks`, and `getAudioTracks`. And, you can filter the tracks your own by using their metadata.

**Comment by fatukunda** [comment]
@lherman-cs @hassanctech To give you context, I'm using the master code in one application and the viewer code in another application. I followed the master and viewer code given in the examples. So, the functionality that I'm failing to achieve is to know when the viewer, for example, mutes their video. I would like that when the viewer mutes their video, I show a message telling the master that the viewer has stopped sharing the video and vice versa. I've used the mute event but it doesn't seem to work.

**Comment by lherman-cs** [comment]
@fatukunda for more flexibilities, you'd probably want to use a data channel instead to send these custom events.

**Comment by fatukunda** [comment]
@lherman-cs I've tried to use the dataChannel but can't seem to be able to send the messages. A working example for using the dataChannel would really help.

**Comment by lherman-cs** [comment]
@fatukunda since this is related to the browser APIs, I would suggest to look outside of KVS. https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Simple_RTCDataChannel_sample might be useful to understand how data channel works in the browser environment.

**Comment by fatukunda** [comment]
Thanks @lherman-cs I managed to use the data channel to send messages and then using those messages to conditionally render parts of my UI.
