### ISSUE TITLE
Signaling client error: TypeError: Cannot read property 'digest' of undefined

### ISSUE THREAD

**Issue by Morras** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#93]
I am trying to create my own viewer following the example given in the repo.

In my html file, I link to the two js libraries:
```
https://sdk.amazonaws.com/js/aws-sdk-2.585.0.min.js
https://unpkg.com/amazon-kinesis-video-streams-webrtc/dist/kvs-webrtc.min.js
```

When I trigger the `startViewer()`, I get the following error:

```
app.js?modified=1599143599:20 [VIEWER] Signaling client error:  TypeError: Cannot read property 'digest' of undefined
    at Function.<anonymous> (kvs-webrtc.min.js:8)
    at kvs-webrtc.min.js:8
    at Object.next (kvs-webrtc.min.js:8)
    at kvs-webrtc.min.js:8
    at new Promise (<anonymous>)
    at Module.l (kvs-webrtc.min.js:8)
    at Function.e.sha256 (kvs-webrtc.min.js:8)
    at e.<anonymous> (kvs-webrtc.min.js:8)
    at kvs-webrtc.min.js:8
    at Object.next (kvs-webrtc.min.js:8)
```

The offending segment of the library seems to be this, where i.default is undefined

```
case 0:return[4,i.default.subtle.digest({name:"SHA-256"},this.toUint8Array(e))];
```

Any help in tracking down my error will be much appreciated.

**Comment by lherman-cs** [comment]
@Morras Would you mind to share a snippet where it crashes?

**Comment by Morras** [comment]
I found that the problem is that while I am working on this on my development machine, I am serving the traffic locally over http and not https.  However WebCrypto is only available from a "secure origin" which is essentially either https, or local host.
When I tested this with local host it worked fine. 

You can read more about that here: https://chromium.googlesource.com/chromium/src/+/master/docs/security/faq.md#why-are-some-web-platform-features-only-available-in-https-page_loads
