### ISSUE TITLE
How to mute call and video stop stream using kinesis webrtc

### ISSUE THREAD

**Issue by naveedaziz** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#96]
How to mute call and video stop stream using kinesis webrtc ?

**Comment by aspdev91** [comment]
+1 I'm curious about how to do this as well as screen share

**Comment by kpatil001** [comment]
For someone who is stuck on this.

To implement mute call functionality, we can enable and disable the video or audio tracks which we add to RTCPeerConnection object.  This might help [https://stackoverflow.com/a/61082244/10110652](https://stackoverflow.com/a/61082244/10110652).
When we disable these MediaStreamTrack, it will stream silence and/or darkness.  
[https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled](https://developer.mozilla.org/en-US/docs/Web/API/MediaStreamTrack/enabled)

**Comment by disa6302** [comment]
Closing since it has gone stale.
