### ISSUE TITLE
A example of one-to-many peer connections?

### ISSUE THREAD

**Issue by chai2** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#98]
While the test page example works well, I'm wondering if there is an example for multiple peer connections?

GCloud has this well fleshed out demo - https://appr.tc/ and wondering if there are similar plans for AWSLabs team to do something similar?

**Comment by chadlittle** [comment]
What part are you hung up on specifically? There is an example of a master, and an example of a viewer. What else do you need to implement one-to-many?

**Comment by chai2** [comment]
I tried with the example of a master and viewer. It works for 1 master and 1 viewer. If I open another session, viewer 2 video doesn't load, and viewer 1 "remote-view" will be stuck.

**Comment by sirknightj** [comment]
See #241.
