### ISSUE TITLE
Failed to connect when there are more than 3 peers

### ISSUE THREAD

**Issue by lherman-cs** [awslabs/amazon-kinesis-video-streams-webrtc-sdk-js#99]
> Dear, actually the problem i am getting is when i connect user more than 3 in the conference call. It start behaving strange and random disconnects happens with multiple users. Can you help in that.

This is a continuation from https://github.com/awslabs/amazon-kinesis-video-streams-webrtc-sdk-js/issues/95#issuecomment-695750849.

**Comment by MushMal** [comment]
@naveedaziz  could you please provide detailed information on what's going on including debug logs. As is, this is not an actionable issue.

**Comment by MushMal** [comment]
Resolving as stale
